// Generated by specs/bip388/gen.py. DO NOT EDIT.
// clang-format off

static const char *const vec_000_ct[] = {
    "Spendable by @0 alone (Legacy)",
};
static const char *const vec_001_ct[] = {
    "Spendable by @0 alone (SegWit)",
};
static const char *const vec_002_ct[] = {
    "Spendable by @0 alone (SegWit)",
};
static const char *const vec_003_ct[] = {
    "Each of @0 and @1 must sign",
};
static const char *const vec_004_ct[] = {
    "Any 2 of @0, @1 and @2 must sign",
};
static const char *const vec_005_ct[] = {
    "Each of @0, @1 and @2 must sign",
};
static const char *const vec_006_ct[] = {
    "Each of @0 and @1 must sign",
};
static const char *const vec_007_ct[] = {
    "Each of @0 and @1 must sign",
};
static const char *const vec_008_ct[] = {
    "Each of @0 and @1 must sign",
};
static const char *const vec_009_ct[] = {
    "Any 2 of @0, @1 and @2 must sign",
};
static const char *const vec_010_ct[] = {
    "Each of @0, @1 and @2 must sign",
};
static const char *const vec_011_ct[] = {
    "Each of @0, @1 and @2 must sign",
};
static const char *const vec_012_ct[] = {
    "Each of @0 and @1 must sign",
};
static const char *const vec_013_ct[] = {
    "Any 2 of @0, @1 and @2 must sign",
};
static const char *const vec_014_ct[] = {
    "Spendable by @0 alone (Taproot)",
};
static const char *const vec_015_ct[] = {
    "Main path: spendable by @0",
    "@1 must sign",
};
static const char *const vec_016_ct[] = {
    "Main path: spendable by @0",
    "@1 must sign",
    "@2 must sign",
};
static const char *const vec_017_ct[] = {
    "Main path: spendable by @0",
    "@3 must sign",
    "Each of @1 and @2 must sign (sorted)",
};
static const char *const vec_018_ct[] = {
    "Main path: spendable by @0",
    "@1 must sign",
    "@2 must sign",
    "@3 must sign",
};
static const char *const vec_019_ct[] = {
    "Main path: spendable by @0",
    "@1 must sign",
    "@2 must sign",
};
static const char *const vec_020_ct[] = {
    "Main path: spendable by @0",
    "@1 must sign, 1000 blocks after receiving",
    "@2 must sign, 2000 blocks after receiving",
};
static const char *const vec_021_ct[] = {
    "Main path: spendable by @0",
    "Each of @4 and @5 must sign",
    "Any 2 of @1, @2 and @3 must sign",
};
static const char *const vec_022_ct[] = {
    "Main path: spendable by @0",
    "Any 2 of @4, @5 and @6 must sign",
    "Each of @1, @2 and @3 must sign",
};
static const char *const vec_023_ct[] = {
    "Main path: spendable by @0",
    "Any 2 of @1, @2 and @3 must sign",
    "Any 2 of @4, @5 and @6 must sign",
};
static const char *const vec_024_ct[] = {
    "Main path: spendable by @0",
    "Each of @1 and @2 must sign (sorted)",
    "Each of @4 and @5 must sign (sorted)",
};
static const char *const vec_025_ct[] = {
    "Main path: spendable by @0",
    "Each of @10 and @11 must sign",
    "Any 2 of @1, @2 and @3 must sign",
    "Any 2 of @4, @5 and @6 must sign",
    "Each of @7, @8 and @9 must sign",
};
static const char *const vec_026_ct[] = {
    "Main path: spendable by @0",
    "@1 must sign, 960 blocks after receiving",
    "Raw policy: t:or_c(pk(@2/**),and_v(v:pk(@3/**),or_c(pk(@4/**),v:ripemd160(907cd521fff981ce4063a4dc43c6f3fd28e08995))))",
};
static const char *const vec_027_ct[] = {
    "Main path: spendable by @0",
    "@1 must sign",
    "Raw policy: t:or_c(pk(@2/**),and_v(v:pk(@3/**),or_c(pk(@4/**),v:ripemd160(907cd521fff981ce4063a4dc43c6f3fd28e08995))))",
};
static const char *const vec_028_ct[] = {
    "Main path: spendable by @0",
    "@1 must sign, 52560 blocks after receiving",
};
static const char *const vec_029_ct[] = {
    "Main path: spendable by @0",
    "@1 must sign",
    "@2 must sign, 52560 blocks after receiving",
};
static const char *const vec_030_ct[] = {
    "Main path: spendable by @0",
    "@1 must sign",
    "@2 must sign, 1008 blocks after receiving",
};
static const char *const vec_031_ct[] = {
    "Main path: spendable by @0",
    "Each of @1, @2 and @3 must sign",
    "Any 2 of @4, @5, @6, @7 and @8 must sign",
};
static const char *const vec_032_ct[] = {
    "Main path: spendable by @0",
    "@1 must sign, 8 minutes 32 seconds after receiving",
};
static const char *const vec_033_ct[] = {
    "Main path: spendable by @0",
    "@1 must sign",
    "@2 must sign, 8 minutes 32 seconds after receiving",
};
static const char *const vec_034_ct[] = {
    "Main path: spendable by @0",
    "@1 must sign",
    "@2 must sign, 1 day 1 hour 36 minutes after receiving",
};
static const char *const vec_035_ct[] = {
    "Main path: spendable by @0",
    "@1 must sign",
    "Each of @2 and @3 must sign, 1 day 1 hour 36 minutes after receiving",
};
static const char *const vec_036_ct[] = {
    "Main path: spendable by @0",
    "@1 must sign, not before block 840000",
};
static const char *const vec_037_ct[] = {
    "Main path: spendable by @0",
    "@1 must sign",
    "Each of @2 and @3 must sign, not before block 840000",
};
static const char *const vec_038_ct[] = {
    "Main path: spendable by @0",
    "@1 must sign, not before 1985-11-05 00:53:20 UTC",
};
static const char *const vec_039_ct[] = {
    "Main path: spendable by @0",
    "@1 must sign, not before 2020-01-01 UTC",
};
static const char *const vec_040_ct[] = {
    "Main path: spendable by @0",
    "@1 must sign",
    "Each of @2 and @3 must sign, not before 2023-11-14 22:13:20 UTC",
};
static const char *const vec_041_ct[] = {
    "Main path: spendable by @0",
    "@1 must sign, 1000 blocks after receiving",
    "@1 must sign, 2000 blocks after receiving",
};
static const char *const vec_042_ct[] = {
    "Main path: spendable by @0",
    "@1 must sign, 1000 blocks after receiving",
    "@1 must sign, not before block 840000",
};
static const char *const vec_043_ct[] = {
    "Main path: spendable by @0",
    "@1 must sign, 1000 blocks after receiving",
    "@1 must sign, 1000 blocks after receiving",
};
static const char *const vec_044_ct[] = {
    "Main path: spendable by @0",
    "@1 and @2 must both sign, 1008 blocks after receiving",
};
static const char *const vec_045_ct[] = {
    "Main path: spendable by @0",
    "@1 must sign",
    "@2 and @3 must both sign, 1008 blocks after receiving",
};
static const char *const vec_046_ct[] = {
    "Main path: spendable by @0",
    "@1 and @2 must both sign, 1 day 1 hour 36 minutes after receiving",
};
static const char *const vec_047_ct[] = {
    "Main path: spendable by @0",
    "@1 and @2 must both sign, not before block 840000",
};
static const char *const vec_048_ct[] = {
    "Main path: spendable by @0",
    "@1 and @2 must both sign, not before 2023-11-14 22:13:20 UTC",
};
static const char *const vec_049_ct[] = {
    "Each of @0 and @1 must sign",
};
static const char *const vec_050_ct[] = {
    "Each of @0, @1 and @2 must sign",
};
static const char *const vec_051_ct[] = {
    "Main path: each of @0 and @1 must sign",
    "@2 must sign",
};
static const char *const vec_052_ct[] = {
    "Main path: each of @0 and @1 must sign",
    "@2 must sign",
    "@3 must sign",
};
static const char *const vec_053_ct[] = {
    "Main path: each of @0 and @1 must sign",
    "@2 must sign",
    "@3 must sign",
    "@4 must sign",
};
static const char *const vec_054_ct[] = {
    "Main path: each of @0 and @1 must sign",
    "@2 must sign, 1008 blocks after receiving",
};
static const char *const vec_055_ct[] = {
    "Main path: each of @0 and @1 must sign",
    "@2 must sign",
    "@3 must sign, not before block 840000",
};
static const char *const vec_056_ct[] = {
    "Main path: spendable by @0",
    "Each of @1, @2 and @3 must sign",
};
static const char *const vec_057_ct[] = {
    "Main path: spendable by @0",
    "Each of @1 and @2 must sign",
};
static const char *const vec_058_ct[] = {
    "Main path: spendable by @0",
    "Each of @1, @2 and @3 must sign",
};
static const char *const vec_059_ct[] = {
    "Main path: spendable by @0",
    "Each of @1 and @2 must sign, 1008 blocks after receiving",
};
static const char *const vec_060_ct[] = {
    "Main path: spendable by @0",
    "Each of @1 and @2 must sign, 1 day 1 hour 36 minutes after receiving",
};
static const char *const vec_061_ct[] = {
    "Main path: spendable by @0",
    "Each of @1 and @2 must sign, not before block 840000",
};
static const char *const vec_062_ct[] = {
    "Main path: spendable by @0",
    "Each of @1 and @2 must sign, not before 2023-11-14 22:13:20 UTC",
};
static const char *const vec_063_ct[] = {
    "Main path: spendable by @0",
    "@1 must sign",
    "Each of @2 and @3 must sign",
};
static const char *const vec_064_ct[] = {
    "Main path: spendable by @0",
    "Each of @4 and @5 must sign",
    "Any 2 of @1, @2 and @3 must sign",
};
static const char *const vec_065_ct[] = {
    "Main path: spendable by @0",
    "Raw policy: multi_a(2,musig(@1,@2)/**,@3/**)",
};
static const char *const vec_066_ct[] = {
    "Main path: spendable by @0",
    "Raw policy: sortedmulti_a(2,musig(@1,@2)/**,@3/**)",
};
static const char *const vec_067_ct[] = {
    "Main path: spendable by @0",
    "@1 must sign",
    "Raw policy: multi_a(2,musig(@2,@3)/**,@4/**)",
};
static const char *const vec_068_ct[] = {
    "Main path: spendable by @0",
    "Raw policy: and_v(v:multi_a(2,musig(@1,@2)/**,@3/**),older(1008))",
};
static const char *const vec_069_ct[] = {
    "Main path: spendable by @0",
    "@2 and @1 must both sign",
    "@1 must sign, 4383 blocks after receiving",
};
static const char *const vec_070_ct[] = {
    "Main path: spendable by @0",
    "@1 and @2 must both sign",
    "Any 2 of @1, @2 and @3 must sign, 144 blocks after receiving",
};
static const char *const vec_071_ct[] = {
    "Main path: spendable by @0",
    "@0 must sign",
};
static const char *const vec_072_ct[] = {
    "Main path: spendable by @0",
    "@0 must sign",
};
static const char *const vec_073_ct[] = {
    "Main path: spendable by @0",
    "Each of @1 and @2 must sign",
    "Each of @1 and @2 must sign",
};
static const char *const vec_074_ct[] = {
    "Main path: spendable by @0",
    "@0 must sign",
    "@0 must sign",
};
static const char *const vec_075_ct[] = {
    "Main path: spendable by @0",
    "@1 must sign",
    "@1 must sign",
};
static const char *const vec_076_ct[] = {
    "Main path: spendable by @0",
    "@1 must sign",
    "@1 must sign, 4383 blocks after receiving",
};
static const char *const vec_077_ct[] = {
    "Main path: spendable by @0",
    "@0 must sign",
    "@1 and @1 must both sign",
};
static const char *const vec_078_ct[] = {
    "Main path: each of @0, @1 and @2 must sign",
    "Each of @0 and @1 must sign, 1 day 1 hour 36 minutes after receiving",
    "Each of @0 and @2 must sign, 1 day 1 hour 36 minutes after receiving",
    "Each of @1 and @2 must sign, 1 day 1 hour 36 minutes after receiving",
};
static const char *const vec_079_ct[] = {
    "Main path: spendable by @0",
    "@1 must sign - and also - each of @2 and @3 must sign",
};
static const char *const vec_080_ct[] = {
    "Main path: spendable by @0",
    "@1 must sign - and also - each of @2 and @3 must sign",
};
static const char *const vec_081_ct[] = {
    "Main path: spendable by @0",
    "@1 must sign - and also - each of @2 and @3 must sign",
};
static const char *const vec_082_ct[] = {
    "Main path: spendable by @0",
    "Each of @1 and @2 must sign - and also - each of @3 and @4 must sign",
};
static const char *const vec_083_ct[] = {
    "Main path: spendable by @0",
    "@1 and @2 must both sign - and also - each of @3 and @4 must sign",
};
static const char *const vec_084_ct[] = {
    "Main path: spendable by @0",
    "@1 must sign",
    "@2 must sign - and also - each of @3 and @4 must sign",
};
static const char *const vec_085_ct[] = {
    "pkh(@0/<2;3>/*)",
};
static const char *const vec_086_ct[] = {
    "wpkh(@0/<0;2>/*)",
};
static const char *const vec_087_ct[] = {
    "tr(@0/<4;5>/*)",
};
static const char *const vec_088_ct[] = {
    "tr(@0/**,pk(@1/<2;3>/*))",
};
static const char *const vec_089_ct[] = {
    "wsh(and_v(v:pk(@0/**),pk(@1/**)))",
};

static const ct_vector_t CT_VECTORS[] = {
    { .template_str = "pkh(@0/**)", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_000_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "wpkh(@0/**)", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_001_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "sh(wpkh(@0/**))", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_002_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "wsh(sortedmulti(2,@0/**,@1/**))", .has_confusion_score = true, .confusion_score = 7ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_003_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "wsh(sortedmulti(2,@0/**,@1/**,@2/**))", .has_confusion_score = true, .confusion_score = 6ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_004_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "wsh(sortedmulti(3,@0/**,@1/**,@2/**))", .has_confusion_score = true, .confusion_score = 7ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_005_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "wsh(multi(2,@0/**,@1/**))", .has_confusion_score = true, .confusion_score = 7ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_006_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "sh(wsh(multi(2,@0/**,@1/**)))", .has_confusion_score = true, .confusion_score = 7ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_007_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "sh(wsh(sortedmulti(2,@0/**,@1/**)))", .has_confusion_score = true, .confusion_score = 7ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_008_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "sh(wsh(multi(2,@0/**,@1/**,@2/**)))", .has_confusion_score = true, .confusion_score = 6ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_009_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "sh(wsh(sortedmulti(3,@0/**,@1/**,@2/**)))", .has_confusion_score = true, .confusion_score = 7ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_010_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "wsh(multi(3,@0/**,@1/**,@2/**))", .has_confusion_score = true, .confusion_score = 7ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_011_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "sh(multi(2,@0/**,@1/**))", .has_confusion_score = true, .confusion_score = 7ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_012_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "sh(sortedmulti(2,@0/**,@1/**,@2/**))", .has_confusion_score = true, .confusion_score = 6ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_013_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**)", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_014_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,pk(@1/**))", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_015_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{pk(@1/**),pk(@2/**)})", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_016_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{sortedmulti_a(2,@1/**,@2/**),pk(@3/**)})", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_017_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{{pk(@1/**),pk(@2/**)},pk(@3/**)})", .has_confusion_score = true, .confusion_score = 3ULL, .has_cleartext_array = true, .cleartext_n = 4, .cleartext = vec_018_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{pk(@2/**),pk(@1/**)})", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_019_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{and_v(v:pk(@2/<0;1>/*),older(2000)),and_v(v:pk(@1/<0;1>/*),older(1000))})", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_020_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{multi_a(2,@1/**,@2/**,@3/**),multi_a(2,@4/**,@5/**)})", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_021_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{multi_a(3,@1/**,@2/**,@3/**),multi_a(2,@4/**,@5/**,@6/**)})", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_022_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{multi_a(2,@4/**,@5/**,@6/**),multi_a(2,@1/**,@2/**,@3/**)})", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_023_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{sortedmulti_a(2,@4/**,@5/**),sortedmulti_a(2,@1/**,@2/**)})", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_024_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{multi_a(3,@7/**,@8/**,@9/**),{multi_a(2,@4/**,@5/**,@6/**),{multi_a(2,@1/**,@2/**,@3/**),multi_a(2,@10/**,@11/**)}}})", .has_confusion_score = true, .confusion_score = 60ULL, .has_cleartext_array = true, .cleartext_n = 5, .cleartext = vec_025_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{and_v(v:pk(@1/**),older(960)),t:or_c(pk(@2/**),and_v(v:pk(@3/**),or_c(pk(@4/**),v:ripemd160(907cd521fff981ce4063a4dc43c6f3fd28e08995))))})", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_026_ct, .has_has_cleartext = true, .cleartext_flag = false },
    { .template_str = "tr(@0/**,{t:or_c(pk(@2/**),and_v(v:pk(@3/**),or_c(pk(@4/**),v:ripemd160(907cd521fff981ce4063a4dc43c6f3fd28e08995)))),pk(@1/**)})", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_027_ct, .has_has_cleartext = true, .cleartext_flag = false },
    { .template_str = "tr(@0/**,and_v(v:pk(@1/<0;1>/*),older(52560)))", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_028_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{pk(@1/**),and_v(v:pk(@2/<0;1>/*),older(52560))})", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_029_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{pk(@1/**),and_v(v:pk(@2/<0;1>/*),older(1008))})", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_030_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{multi_a(3,@1/**,@2/**,@3/**),multi_a(2,@4/**,@5/**,@6/**,@7/**,@8/**)})", .has_confusion_score = false, .confusion_score = 0ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_031_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,and_v(v:pk(@1/<0;1>/*),older(4194305)))", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_032_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{pk(@1/**),and_v(v:pk(@2/<0;1>/*),older(4194305))})", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_033_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{pk(@1/**),and_v(v:pk(@2/<0;1>/*),older(4194484))})", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_034_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{pk(@1/**),and_v(v:multi_a(2,@2/<0;1>/*,@3/<0;1>/*),older(4194484))})", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_035_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,and_v(v:pk(@1/<0;1>/*),after(840000)))", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_036_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{pk(@1/**),and_v(v:multi_a(2,@2/<0;1>/*,@3/<0;1>/*),after(840000))})", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_037_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,and_v(v:pk(@1/<0;1>/*),after(500000000)))", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_038_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,and_v(v:pk(@1/<0;1>/*),after(1577836800)))", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_039_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{pk(@1/**),and_v(v:multi_a(2,@2/<0;1>/*,@3/<0;1>/*),after(1700000000))})", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_040_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{and_v(v:pk(@1/<0;1>/*),older(1000)),and_v(v:pk(@1/<2;3>/*),older(2000))})", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_041_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{and_v(v:pk(@1/<0;1>/*),older(1000)),and_v(v:pk(@1/<2;3>/*),after(840000))})", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_042_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{and_v(v:pk(@1/<0;1>/*),older(1000)),and_v(v:pk(@1/<2;3>/*),older(1000))})", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_043_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,and_v(v:and_v(v:pk(@1/<0;1>/*),pk(@2/<0;1>/*)),older(1008)))", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_044_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{pk(@1/**),and_v(v:and_v(v:pk(@2/<0;1>/*),pk(@3/<0;1>/*)),older(1008))})", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_045_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,and_v(v:and_v(v:pk(@1/<0;1>/*),pk(@2/<0;1>/*)),older(4194484)))", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_046_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,and_v(v:and_v(v:pk(@1/<0;1>/*),pk(@2/<0;1>/*)),after(840000)))", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_047_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,and_v(v:and_v(v:pk(@1/<0;1>/*),pk(@2/<0;1>/*)),after(1700000000)))", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_048_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(musig(@0,@1)/**)", .has_confusion_score = true, .confusion_score = 7ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_049_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(musig(@0,@1,@2)/**)", .has_confusion_score = true, .confusion_score = 7ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_050_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(musig(@0,@1)/**,pk(@2/**))", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_051_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(musig(@0,@1)/**,{pk(@2/**),pk(@3/**)})", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_052_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(musig(@0,@1)/**,{{pk(@2/**),pk(@3/**)},pk(@4/**)})", .has_confusion_score = true, .confusion_score = 3ULL, .has_cleartext_array = true, .cleartext_n = 4, .cleartext = vec_053_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(musig(@0,@1)/**,and_v(v:pk(@2/<0;1>/*),older(1008)))", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_054_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(musig(@0,@1)/**,{pk(@2/**),and_v(v:pk(@3/<0;1>/*),after(840000))})", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_055_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,multi_a(3,@1/**,@2/**,@3/**))", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_056_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,pk(musig(@1,@2)/**))", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_057_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,pk(musig(@1,@2,@3)/**))", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_058_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,and_v(v:pk(musig(@1,@2)/**),older(1008)))", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_059_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,and_v(v:pk(musig(@1,@2)/**),older(4194484)))", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_060_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,and_v(v:pk(musig(@1,@2)/**),after(840000)))", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_061_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,and_v(v:pk(musig(@1,@2)/**),after(1700000000)))", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_062_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{pk(@1/**),pk(musig(@2,@3)/**)})", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_063_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{multi_a(2,@1/**,@2/**,@3/**),pk(musig(@4,@5)/**)})", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_064_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,multi_a(2,musig(@1,@2)/**,@3/**))", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_065_ct, .has_has_cleartext = true, .cleartext_flag = false },
    { .template_str = "tr(@0/**,sortedmulti_a(2,musig(@1,@2)/**,@3/**))", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_066_ct, .has_has_cleartext = true, .cleartext_flag = false },
    { .template_str = "tr(@0/**,{pk(@1/**),multi_a(2,musig(@2,@3)/**,@4/**)})", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_067_ct, .has_has_cleartext = true, .cleartext_flag = false },
    { .template_str = "tr(@0/**,and_v(v:multi_a(2,musig(@1,@2)/**,@3/**),older(1008)))", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_068_ct, .has_has_cleartext = true, .cleartext_flag = false },
    { .template_str = "tr(@0/<0;1>/*,{and_v(v:pk(@1/<0;1>/*),older(4383)),and_v(v:pk(@2/<0;1>/*),pk(@1/<2;3>/*))})", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_069_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/<0;1>/*,{and_v(v:multi_a(2,@1/<0;1>/*,@2/<0;1>/*,@3/<0;1>/*),older(144)),and_v(v:pk(@1/<2;3>/*),pk(@2/<2;3>/*))})", .has_confusion_score = true, .confusion_score = 4ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_070_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/<0;1>/*,pk(@0/<2;3>/*))", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_071_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/<2;3>/*,pk(@0/<0;1>/*))", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_072_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{multi_a(2,@1/<0;1>/*,@2/<0;1>/*),multi_a(2,@1/<2;3>/*,@2/<2;3>/*)})", .has_confusion_score = true, .confusion_score = 16ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_073_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/<0;1>/*,{pk(@0/<2;3>/*),pk(@0/<4;5>/*)})", .has_confusion_score = true, .confusion_score = 6ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_074_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{pk(@1/<0;1>/*),pk(@1/<2;3>/*)})", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_075_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{and_v(v:pk(@1/<0;1>/*),older(4383)),pk(@1/<2;3>/*)})", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_076_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/<0;1>/*,{pk(@0/<2;3>/*),and_v(v:pk(@1/<0;1>/*),pk(@1/<2;3>/*))})", .has_confusion_score = true, .confusion_score = 4ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_077_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(musig(@0,@1,@2)/**,{and_v(v:pk(musig(@0,@1)/**),older(4194484)),{and_v(v:pk(musig(@0,@2)/**),older(4194484)),and_v(v:pk(musig(@1,@2)/**),older(4194484))}})", .has_confusion_score = true, .confusion_score = 5184ULL, .has_cleartext_array = true, .cleartext_n = 4, .cleartext = vec_078_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,and_v(v:pk(@1/**),multi_a(2,@2/**,@3/**)))", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_079_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,and_v(v:pk(@1/**),pk(musig(@2,@3)/**)))", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_080_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,and_v(v:pk(@1/**),multi_a(2,@2/**,@3/**)))", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_081_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,and_v(v:multi_a(2,@1/**,@2/**),multi_a(2,@3/**,@4/**)))", .has_confusion_score = true, .confusion_score = 4ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_082_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,and_v(v:and_v(v:pk(@1/**),pk(@2/**)),multi_a(2,@3/**,@4/**)))", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_083_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{pk(@1/**),and_v(v:pk(@2/**),multi_a(2,@3/**,@4/**))})", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_084_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "pkh(@0/<2;3>/*)", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_085_ct, .has_has_cleartext = true, .cleartext_flag = false },
    { .template_str = "wpkh(@0/<0;2>/*)", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_086_ct, .has_has_cleartext = true, .cleartext_flag = false },
    { .template_str = "tr(@0/<4;5>/*)", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_087_ct, .has_has_cleartext = true, .cleartext_flag = false },
    { .template_str = "tr(@0/**,pk(@1/<2;3>/*))", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_088_ct, .has_has_cleartext = true, .cleartext_flag = false },
    { .template_str = "wsh(and_v(v:pk(@0/**),pk(@1/**)))", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_089_ct, .has_has_cleartext = true, .cleartext_flag = false },
};
static const size_t CT_VECTORS_N = sizeof(CT_VECTORS) / sizeof(CT_VECTORS[0]);

