// Generated by dev-tools/gen_cleartext/gen.py. DO NOT EDIT.
// clang-format off

static const char *const vec_000_ct[] = {
    "Legacy single-signature (@0)",
};
static const char *const vec_001_ct[] = {
    "Segwit single-signature (@0)",
};
static const char *const vec_002_ct[] = {
    "Segwit single-signature (@0)",
};
static const char *const vec_003_ct[] = {
    "2 of @0 and @1 (SegWit)",
};
static const char *const vec_004_ct[] = {
    "2 of @0, @1 and @2 (SegWit)",
};
static const char *const vec_005_ct[] = {
    "3 of @0, @1 and @2 (SegWit)",
};
static const char *const vec_006_ct[] = {
    "2 of @0 and @1 (SegWit)",
};
static const char *const vec_007_ct[] = {
    "2 of @0 and @1 (SegWit)",
};
static const char *const vec_008_ct[] = {
    "2 of @0 and @1 (SegWit)",
};
static const char *const vec_009_ct[] = {
    "2 of @0, @1 and @2 (SegWit)",
};
static const char *const vec_010_ct[] = {
    "3 of @0, @1 and @2 (SegWit)",
};
static const char *const vec_011_ct[] = {
    "Primary path: @0",
};
static const char *const vec_012_ct[] = {
    "Primary path: @0",
    "Single-signature (@1)",
};
static const char *const vec_013_ct[] = {
    "Primary path: @0",
    "Single-signature (@1)",
    "Single-signature (@2)",
};
static const char *const vec_014_ct[] = {
    "Primary path: @0",
    "Single-signature (@3)",
    "2 of @1 and @2 (sorted)",
};
static const char *const vec_015_ct[] = {
    "Primary path: @0",
    "Single-signature (@1)",
    "Single-signature (@2)",
    "Single-signature (@3)",
};
static const char *const vec_016_ct[] = {
    "Primary path: @0",
    "Single-signature (@1)",
    "Single-signature (@2)",
};
static const char *const vec_017_ct[] = {
    "Primary path: @0",
    "Single-signature (@1) after 1000 blocks",
    "Single-signature (@2) after 2000 blocks",
};
static const char *const vec_018_ct[] = {
    "Primary path: @0",
    "2 of @4 and @5",
    "2 of @1, @2 and @3",
};
static const char *const vec_019_ct[] = {
    "Primary path: @0",
    "Single-signature (@1) after 960 blocks",
    "t:or_c(pk(@2/**),and_v(v:pk(@3/**),or_c(pk(@4/**),v:ripemd160(907cd521fff981ce4063a4dc43c6f3fd28e08995))))",
};
static const char *const vec_020_ct[] = {
    "Primary path: @0",
    "Single-signature (@1) after 52560 blocks",
};
static const char *const vec_021_ct[] = {
    "Primary path: @0",
    "Single-signature (@1)",
    "Single-signature (@2) after 52560 blocks",
};
static const char *const vec_022_ct[] = {
    "Primary path: @0",
    "Single-signature (@1)",
    "Single-signature (@2) after 1008 blocks",
};
static const char *const vec_023_ct[] = {
    "Primary path: @0",
    "Single-signature (@1) after 8m 32s",
};
static const char *const vec_024_ct[] = {
    "Primary path: @0",
    "Single-signature (@1)",
    "Single-signature (@2) after 8m 32s",
};
static const char *const vec_025_ct[] = {
    "Primary path: @0",
    "Single-signature (@1)",
    "Single-signature (@2) after 1d 1h 36m",
};
static const char *const vec_026_ct[] = {
    "Primary path: @0",
    "Single-signature (@1)",
    "2 of @2 and @3 after 1d 1h 36m",
};
static const char *const vec_027_ct[] = {
    "Primary path: @0",
    "Single-signature (@1) after block height 840000",
};
static const char *const vec_028_ct[] = {
    "Primary path: @0",
    "Single-signature (@1)",
    "2 of @2 and @3 after block height 840000",
};
static const char *const vec_029_ct[] = {
    "Primary path: @0",
    "Single-signature (@1) after date 1985-11-05 00:53:20",
};
static const char *const vec_030_ct[] = {
    "Primary path: @0",
    "Single-signature (@1)",
    "2 of @2 and @3 after date 2023-11-14 22:13:20",
};
static const char *const vec_031_ct[] = {
    "Primary path: @0",
    "Both @1 and @2 must sign after 1008 blocks",
};
static const char *const vec_032_ct[] = {
    "Primary path: @0",
    "Single-signature (@1)",
    "Both @2 and @3 must sign after 1008 blocks",
};
static const char *const vec_033_ct[] = {
    "Primary path: @0",
    "Both @1 and @2 must sign after 1d 1h 36m",
};
static const char *const vec_034_ct[] = {
    "Primary path: @0",
    "Both @1 and @2 must sign after block height 840000",
};
static const char *const vec_035_ct[] = {
    "Primary path: @0",
    "Both @1 and @2 must sign after date 2023-11-14 22:13:20",
};
static const char *const vec_036_ct[] = {
    "Primary path: 2 of @0 and @1",
};
static const char *const vec_037_ct[] = {
    "Primary path: 3 of @0, @1 and @2",
};
static const char *const vec_038_ct[] = {
    "Primary path: 2 of @0 and @1",
    "Single-signature (@2)",
};
static const char *const vec_039_ct[] = {
    "Primary path: 2 of @0 and @1",
    "Single-signature (@2)",
    "Single-signature (@3)",
};
static const char *const vec_040_ct[] = {
    "Primary path: 2 of @0 and @1",
    "Single-signature (@2)",
    "Single-signature (@3)",
    "Single-signature (@4)",
};
static const char *const vec_041_ct[] = {
    "Primary path: 2 of @0 and @1",
    "Single-signature (@2) after 1008 blocks",
};
static const char *const vec_042_ct[] = {
    "Primary path: 2 of @0 and @1",
    "Single-signature (@2)",
    "Single-signature (@3) after block height 840000",
};
static const char *const vec_043_ct[] = {
    "Primary path: @0",
    "2 of @1 and @2",
};
static const char *const vec_044_ct[] = {
    "Primary path: @0",
    "3 of @1, @2 and @3",
};
static const char *const vec_045_ct[] = {
    "Primary path: @0",
    "2 of @1 and @2 after 1008 blocks",
};
static const char *const vec_046_ct[] = {
    "Primary path: @0",
    "2 of @1 and @2 after 1d 1h 36m",
};
static const char *const vec_047_ct[] = {
    "Primary path: @0",
    "2 of @1 and @2 after block height 840000",
};
static const char *const vec_048_ct[] = {
    "Primary path: @0",
    "2 of @1 and @2 after date 2023-11-14 22:13:20",
};
static const char *const vec_049_ct[] = {
    "Primary path: @0",
    "Single-signature (@1)",
    "2 of @2 and @3",
};
static const char *const vec_050_ct[] = {
    "Primary path: @0",
    "2 of @4 and @5",
    "2 of @1, @2 and @3",
};
static const char *const vec_051_ct[] = {
    "Primary path: @0",
    "Both @2 and @1 must sign",
    "Single-signature (@1) after 4383 blocks",
};
static const char *const vec_052_ct[] = {
    "Primary path: @0",
    "Both @1 and @2 must sign",
    "2 of @1, @2 and @3 after 144 blocks",
};
static const char *const vec_053_ct[] = {
    "Primary path: @0",
    "Single-signature (@0)",
};
static const char *const vec_054_ct[] = {
    "Primary path: @0",
    "Single-signature (@0)",
    "Single-signature (@0)",
};
static const char *const vec_055_ct[] = {
    "Primary path: @0",
    "Single-signature (@1)",
    "Single-signature (@1)",
};
static const char *const vec_056_ct[] = {
    "Primary path: @0",
    "Single-signature (@1)",
    "Single-signature (@1) after 4383 blocks",
};
static const char *const vec_057_ct[] = {
    "Primary path: @0",
    "Single-signature (@0)",
    "Both @1 and @1 must sign",
};
static const char *const vec_058_ct[] = {
    "Primary path: 3 of @0, @1 and @2",
    "2 of @0 and @1 after 1d 1h 36m",
    "2 of @0 and @2 after 1d 1h 36m",
    "2 of @1 and @2 after 1d 1h 36m",
};
static const char *const vec_059_ct[] = {
    "Primary path: @0",
    "Single-signature (@1), and 2 of @2 and @3",
};
static const char *const vec_060_ct[] = {
    "Primary path: @0",
    "Single-signature (@1), and 2 of @2 and @3",
};
static const char *const vec_061_ct[] = {
    "Primary path: @0",
    "Single-signature (@1), and 2 of @2 and @3",
};
static const char *const vec_062_ct[] = {
    "Primary path: @0",
    "2 of @1 and @2, and 2 of @3 and @4",
};
static const char *const vec_063_ct[] = {
    "Primary path: @0",
    "Both @1 and @2 must sign, and 2 of @3 and @4",
};
static const char *const vec_064_ct[] = {
    "Primary path: @0",
    "Single-signature (@1)",
    "Single-signature (@2), and 2 of @3 and @4",
};
static const char *const vec_065_ct[] = {
    "pkh(@0/<2;3>/*)",
};
static const char *const vec_066_ct[] = {
    "wpkh(@0/<0;2>/*)",
};
static const char *const vec_067_ct[] = {
    "tr(@0/<4;5>/*)",
};
static const char *const vec_068_ct[] = {
    "tr(@0/**,pk(@1/<2;3>/*))",
};

static const ct_vector_t CT_VECTORS[] = {
    { .template_str = "pkh(@0/**)", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_000_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "wpkh(@0/**)", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_001_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "sh(wpkh(@0/**))", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_002_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "wsh(sortedmulti(2,@0/**,@1/**))", .has_confusion_score = true, .confusion_score = 4ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_003_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "wsh(sortedmulti(2,@0/**,@1/**,@2/**))", .has_confusion_score = true, .confusion_score = 4ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_004_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "wsh(sortedmulti(3,@0/**,@1/**,@2/**))", .has_confusion_score = true, .confusion_score = 4ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_005_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "wsh(multi(2,@0/**,@1/**))", .has_confusion_score = true, .confusion_score = 4ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_006_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "sh(wsh(multi(2,@0/**,@1/**)))", .has_confusion_score = true, .confusion_score = 4ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_007_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "sh(wsh(sortedmulti(2,@0/**,@1/**)))", .has_confusion_score = true, .confusion_score = 4ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_008_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "sh(wsh(multi(2,@0/**,@1/**,@2/**)))", .has_confusion_score = true, .confusion_score = 4ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_009_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "sh(wsh(sortedmulti(3,@0/**,@1/**,@2/**)))", .has_confusion_score = true, .confusion_score = 4ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_010_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**)", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_011_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,pk(@1/**))", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_012_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{pk(@1/**),pk(@2/**)})", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_013_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{sortedmulti_a(2,@1/**,@2/**),pk(@3/**)})", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_014_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{{pk(@1/**),pk(@2/**)},pk(@3/**)})", .has_confusion_score = true, .confusion_score = 3ULL, .has_cleartext_array = true, .cleartext_n = 4, .cleartext = vec_015_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{pk(@2/**),pk(@1/**)})", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_016_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{and_v(v:pk(@2/<0;1>/*),older(2000)),and_v(v:pk(@1/<0;1>/*),older(1000))})", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_017_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{multi_a(2,@1/**,@2/**,@3/**),multi_a(2,@4/**,@5/**)})", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_018_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{and_v(v:pk(@1/**),older(960)),t:or_c(pk(@2/**),and_v(v:pk(@3/**),or_c(pk(@4/**),v:ripemd160(907cd521fff981ce4063a4dc43c6f3fd28e08995))))})", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_019_ct, .has_has_cleartext = true, .cleartext_flag = false },
    { .template_str = "tr(@0/**,and_v(v:pk(@1/<0;1>/*),older(52560)))", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_020_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{pk(@1/**),and_v(v:pk(@2/<0;1>/*),older(52560))})", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_021_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{pk(@1/**),and_v(v:pk(@2/<0;1>/*),older(1008))})", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_022_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,and_v(v:pk(@1/<0;1>/*),older(4194305)))", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_023_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{pk(@1/**),and_v(v:pk(@2/<0;1>/*),older(4194305))})", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_024_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{pk(@1/**),and_v(v:pk(@2/<0;1>/*),older(4194484))})", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_025_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{pk(@1/**),and_v(v:multi_a(2,@2/<0;1>/*,@3/<0;1>/*),older(4194484))})", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_026_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,and_v(v:pk(@1/<0;1>/*),after(840000)))", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_027_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{pk(@1/**),and_v(v:multi_a(2,@2/<0;1>/*,@3/<0;1>/*),after(840000))})", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_028_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,and_v(v:pk(@1/<0;1>/*),after(500000000)))", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_029_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{pk(@1/**),and_v(v:multi_a(2,@2/<0;1>/*,@3/<0;1>/*),after(1700000000))})", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_030_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,and_v(v:and_v(v:pk(@1/<0;1>/*),pk(@2/<0;1>/*)),older(1008)))", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_031_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{pk(@1/**),and_v(v:and_v(v:pk(@2/<0;1>/*),pk(@3/<0;1>/*)),older(1008))})", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_032_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,and_v(v:and_v(v:pk(@1/<0;1>/*),pk(@2/<0;1>/*)),older(4194484)))", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_033_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,and_v(v:and_v(v:pk(@1/<0;1>/*),pk(@2/<0;1>/*)),after(840000)))", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_034_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,and_v(v:and_v(v:pk(@1/<0;1>/*),pk(@2/<0;1>/*)),after(1700000000)))", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_035_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(musig(@0,@1)/**)", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_036_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(musig(@0,@1,@2)/**)", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_037_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(musig(@0,@1)/**,pk(@2/**))", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_038_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(musig(@0,@1)/**,{pk(@2/**),pk(@3/**)})", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_039_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(musig(@0,@1)/**,{{pk(@2/**),pk(@3/**)},pk(@4/**)})", .has_confusion_score = true, .confusion_score = 3ULL, .has_cleartext_array = true, .cleartext_n = 4, .cleartext = vec_040_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(musig(@0,@1)/**,and_v(v:pk(@2/<0;1>/*),older(1008)))", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_041_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(musig(@0,@1)/**,{pk(@2/**),and_v(v:pk(@3/<0;1>/*),after(840000))})", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_042_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,pk(musig(@1,@2)/**))", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_043_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,pk(musig(@1,@2,@3)/**))", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_044_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,and_v(v:pk(musig(@1,@2)/**),older(1008)))", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_045_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,and_v(v:pk(musig(@1,@2)/**),older(4194484)))", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_046_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,and_v(v:pk(musig(@1,@2)/**),after(840000)))", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_047_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,and_v(v:pk(musig(@1,@2)/**),after(1700000000)))", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_048_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{pk(@1/**),pk(musig(@2,@3)/**)})", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_049_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{multi_a(2,@1/**,@2/**,@3/**),pk(musig(@4,@5)/**)})", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_050_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/<0;1>/*,{and_v(v:pk(@1/<0;1>/*),older(4383)),and_v(v:pk(@2/<0;1>/*),pk(@1/<2;3>/*))})", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_051_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/<0;1>/*,{and_v(v:multi_a(2,@1/<0;1>/*,@2/<0;1>/*,@3/<0;1>/*),older(144)),and_v(v:pk(@1/<2;3>/*),pk(@2/<2;3>/*))})", .has_confusion_score = true, .confusion_score = 4ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_052_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/<0;1>/*,pk(@0/<2;3>/*))", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_053_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/<0;1>/*,{pk(@0/<2;3>/*),pk(@0/<4;5>/*)})", .has_confusion_score = true, .confusion_score = 6ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_054_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{pk(@1/<0;1>/*),pk(@1/<2;3>/*)})", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_055_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{and_v(v:pk(@1/<0;1>/*),older(4383)),pk(@1/<2;3>/*)})", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_056_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/<0;1>/*,{pk(@0/<2;3>/*),and_v(v:pk(@1/<0;1>/*),pk(@1/<2;3>/*))})", .has_confusion_score = true, .confusion_score = 4ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_057_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(musig(@0,@1,@2)/**,{and_v(v:pk(musig(@0,@1)/**),older(4194484)),{and_v(v:pk(musig(@0,@2)/**),older(4194484)),and_v(v:pk(musig(@1,@2)/**),older(4194484))}})", .has_confusion_score = true, .confusion_score = 5184ULL, .has_cleartext_array = true, .cleartext_n = 4, .cleartext = vec_058_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,and_v(v:pk(@1/**),multi_a(2,@2/**,@3/**)))", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_059_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,and_v(v:pk(@1/**),pk(musig(@2,@3)/**)))", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_060_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,and_v(v:pk(@1/**),multi_a(2,@2/**,@3/**)))", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_061_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,and_v(v:multi_a(2,@1/**,@2/**),multi_a(2,@3/**,@4/**)))", .has_confusion_score = true, .confusion_score = 4ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_062_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,and_v(v:and_v(v:pk(@1/**),pk(@2/**)),multi_a(2,@3/**,@4/**)))", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 2, .cleartext = vec_063_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "tr(@0/**,{pk(@1/**),and_v(v:pk(@2/**),multi_a(2,@3/**,@4/**))})", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 3, .cleartext = vec_064_ct, .has_has_cleartext = true, .cleartext_flag = true },
    { .template_str = "pkh(@0/<2;3>/*)", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_065_ct, .has_has_cleartext = true, .cleartext_flag = false },
    { .template_str = "wpkh(@0/<0;2>/*)", .has_confusion_score = true, .confusion_score = 2ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_066_ct, .has_has_cleartext = true, .cleartext_flag = false },
    { .template_str = "tr(@0/<4;5>/*)", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_067_ct, .has_has_cleartext = true, .cleartext_flag = false },
    { .template_str = "tr(@0/**,pk(@1/<2;3>/*))", .has_confusion_score = true, .confusion_score = 1ULL, .has_cleartext_array = true, .cleartext_n = 1, .cleartext = vec_068_ct, .has_has_cleartext = true, .cleartext_flag = false },
};
static const size_t CT_VECTORS_N = sizeof(CT_VECTORS) / sizeof(CT_VECTORS[0]);

