#include <stdarg.h>
#include <stddef.h>
#include <setjmp.h>
#include <cmocka.h>

#include <stdint.h>
#include <stdbool.h>
#include <string.h>

#include "common/bip322.h"
#include "crypto.h"

// ---------------------------------------------------------------------------
// Test vectors
// ---------------------------------------------------------------------------

// The "tx_hashes" table of bip-0322/basic-test-vectors.json (pinned copy in specs/bip322/),
// as generated by specs/bip322/gen.py.
#include "bip322_vectors.inc.c"

// The one hand-written vector: the full serialization of to_spend for "Hello World", spelled
// out field by field. The vectors above only pin txids, which would not tell *which* field is
// wrong if the layout ever regressed; this one does. Its inputs are taken from the vectors.
static const uint8_t TO_SPEND_HELLO_WORLD[] = {
    // nVersion = 0
    0x00,
    0x00,
    0x00,
    0x00,
    // 1 input: null prevout hash, index 0xffffffff
    0x01,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0xff,
    0xff,
    0xff,
    0xff,
    // scriptSig: OP_0 PUSH32(message_hash)
    0x22,
    0x00,
    0x20,
    0xf0,
    0xeb,
    0x03,
    0xb1,
    0xa7,
    0x5a,
    0xc6,
    0xd9,
    0x84,
    0x7f,
    0x55,
    0xc6,
    0x24,
    0xa9,
    0x91,
    0x69,
    0xb5,
    0xdc,
    0xcb,
    0xa2,
    0xa3,
    0x1f,
    0x5b,
    0x23,
    0xbe,
    0xa7,
    0x7b,
    0xa2,
    0x70,
    0xde,
    0x0a,
    0x7a,
    // nSequence = 0
    0x00,
    0x00,
    0x00,
    0x00,
    // 1 output: value 0, the challenge scriptPubKey
    0x01,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x16,
    0x00,
    0x14,
    0x2b,
    0x05,
    0xd5,
    0x64,
    0xe6,
    0xa7,
    0xa3,
    0x3c,
    0x08,
    0x7f,
    0x16,
    0xe0,
    0xf7,
    0x30,
    0xd1,
    0x44,
    0x01,
    0x23,
    0x79,
    0x9d,
    // nLockTime = 0
    0x00,
    0x00,
    0x00,
    0x00};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

static const bip322_tx_hashes_vector_t *find_vector(const char *message_str) {
    for (size_t i = 0; i < BIP322_TX_HASHES_VECTORS_COUNT; i++) {
        if (strcmp(BIP322_TX_HASHES_VECTORS[i].message_str, message_str) == 0) {
            return &BIP322_TX_HASHES_VECTORS[i];
        }
    }
    return NULL;
}

static void sha256d(const uint8_t *data, size_t len, uint8_t out[32]) {
    cx_hash_sha256(data, len, out, 32);
    cx_hash_sha256(out, 32, out, 32);
}

// Serializes the BIP-322 to_sign transaction spending to_spend_txid:0 (test-side
// reimplementation; the app never builds to_sign itself, the client does).
static size_t serialize_to_sign(const uint8_t to_spend_txid[32], uint8_t out[128]) {
    size_t off = 0;
    memset(out + off, 0, 4);  // nVersion = 0
    off += 4;
    out[off++] = 0x01;  // 1 input
    memcpy(out + off, to_spend_txid, 32);
    off += 32;
    memset(out + off, 0, 4);  // prevout index 0
    off += 4;
    out[off++] = 0x00;        // empty scriptSig
    memset(out + off, 0, 4);  // nSequence = 0
    off += 4;
    out[off++] = 0x01;        // 1 output
    memset(out + off, 0, 8);  // value 0
    off += 8;
    out[off++] = 0x01;  // OP_RETURN script
    out[off++] = 0x6a;
    memset(out + off, 0, 4);  // nLockTime = 0
    off += 4;
    return off;
}

// ---------------------------------------------------------------------------
// Tests: to_spend construction
// ---------------------------------------------------------------------------

static void test_bip322_serialize_to_spend_layout(void **state) {
    (void) state;

    const bip322_tx_hashes_vector_t *v = find_vector("Hello World");
    assert_non_null(v);

    uint8_t out[BIP322_TO_SPEND_MAX_LEN];
    int len = bip322_serialize_to_spend(v->message_hash,
                                        v->challenge_script,
                                        v->challenge_script_len,
                                        out);

    assert_int_equal(len, sizeof(TO_SPEND_HELLO_WORLD));
    assert_memory_equal(out, TO_SPEND_HELLO_WORLD, sizeof(TO_SPEND_HELLO_WORLD));
}

static void test_bip322_serialize_to_spend_rejects_long_script(void **state) {
    (void) state;

    uint8_t long_script[MAX_PREVOUT_SCRIPTPUBKEY_LEN + 1] = {0};
    uint8_t out[BIP322_TO_SPEND_MAX_LEN];
    assert_int_equal(bip322_serialize_to_spend(BIP322_TX_HASHES_VECTORS[0].message_hash,
                                               long_script,
                                               sizeof(long_script),
                                               out),
                     -1);
}

// For every vector: the serialized to_spend hashes to the vector's to_spend txid, and so does
// the txid computed by bip322_compute_to_spend_txid().
static void test_bip322_vectors_to_spend_txid(void **state) {
    (void) state;

    for (size_t i = 0; i < BIP322_TX_HASHES_VECTORS_COUNT; i++) {
        const bip322_tx_hashes_vector_t *v = &BIP322_TX_HASHES_VECTORS[i];
        print_message("vector %zu: %s\n", i, v->message_str);

        uint8_t to_spend[BIP322_TO_SPEND_MAX_LEN];
        int len = bip322_serialize_to_spend(v->message_hash,
                                            v->challenge_script,
                                            v->challenge_script_len,
                                            to_spend);
        assert_true(len > 0);

        uint8_t txid[32];
        sha256d(to_spend, (size_t) len, txid);
        assert_memory_equal(txid, v->to_spend_txid, 32);

        memset(txid, 0, sizeof(txid));
        assert_int_equal(bip322_compute_to_spend_txid(v->message_hash,
                                                      v->challenge_script,
                                                      v->challenge_script_len,
                                                      txid),
                         0);
        assert_memory_equal(txid, v->to_spend_txid, 32);
    }
}

// For every vector: the to_sign transaction built on the txid the app computes hashes to the
// vector's to_sign txid. This is what the app's signature ultimately commits to.
static void test_bip322_vectors_to_sign_txid(void **state) {
    (void) state;

    for (size_t i = 0; i < BIP322_TX_HASHES_VECTORS_COUNT; i++) {
        const bip322_tx_hashes_vector_t *v = &BIP322_TX_HASHES_VECTORS[i];

        uint8_t to_spend_txid[32];
        assert_int_equal(bip322_compute_to_spend_txid(v->message_hash,
                                                      v->challenge_script,
                                                      v->challenge_script_len,
                                                      to_spend_txid),
                         0);

        uint8_t to_sign[128];
        size_t len = serialize_to_sign(to_spend_txid, to_sign);

        uint8_t txid[32];
        sha256d(to_sign, len, txid);
        assert_memory_equal(txid, v->to_sign_txid, 32);
    }
}

// ---------------------------------------------------------------------------
// Tests: message hash
// ---------------------------------------------------------------------------

// For every vector: the message hashes to the vector's message_hash.
static void test_bip322_vectors_message_hash(void **state) {
    (void) state;

    for (size_t i = 0; i < BIP322_TX_HASHES_VECTORS_COUNT; i++) {
        const bip322_tx_hashes_vector_t *v = &BIP322_TX_HASHES_VECTORS[i];
        print_message("vector %zu: %s\n", i, v->message_str);

        cx_sha256_t hash_context;
        bip322_message_hash_init(&hash_context);
        crypto_hash_update(&hash_context.header, v->message, v->message_len);
        uint8_t hash[32];
        crypto_hash_digest(&hash_context.header, hash, 32);
        assert_memory_equal(hash, v->message_hash, 32);
    }
}

int main(void) {
    const struct CMUnitTest tests[] = {
        cmocka_unit_test(test_bip322_serialize_to_spend_layout),
        cmocka_unit_test(test_bip322_serialize_to_spend_rejects_long_script),
        cmocka_unit_test(test_bip322_vectors_to_spend_txid),
        cmocka_unit_test(test_bip322_vectors_to_sign_txid),
        cmocka_unit_test(test_bip322_vectors_message_hash),
    };

    return cmocka_run_group_tests(tests, NULL, NULL);
}
