//! C ABI bindings for the `bip388` cleartext API.
//!
//! Exposes parsing of a BIP-388 descriptor template plus the always-compiled
//! `ClearText` operations — `confusion_score` and `to_cleartext` — to C callers
//! (the `cleartext-decode` reverse parser is intentionally excluded). The C side
//! provides all memory: a scratch *arena* the Rust internals allocate from, and
//! an *output* buffer the rendered lines are copied into. Nothing Rust-owned
//! crosses the boundary, so there is nothing for the caller to free.
//!
//! ## Bounded memory, no aborts
//!
//! `bip388`/`bitcoin` use infallible allocation, so once an allocation cannot be
//! satisfied stable Rust can only abort — there is no way to *return* an error
//! from that point. To guarantee a clean error instead, the binding never lets
//! the allocator reach exhaustion: a cheap O(n) pre-scan of the raw descriptor
//! (key-placeholder occurrences, taptree branches, length) computes an upper
//! bound on the working set and, if it exceeds the supplied arena, returns
//! [`Bip388Status::OutOfArena`] (or [`Bip388Status::PolicyTooComplex`] for
//! structurally out-of-range policies) *before* parsing.
//!
//! This takes advantage of the Ledger bitcoin app's policy limits (at most 15
//! keys total and 8 taptree leaves): realistic policies have few placeholder
//! occurrences and fit a 4-8 KiB arena, while pathological inputs are rejected
//! cleanly rather than aborting. See [`required_arena_bytes`] for the model.
//!
//! See `include/bip388.h` (generated by `cbindgen`) for the C-facing contract.

#![cfg_attr(not(feature = "std"), no_std)]

extern crate alloc;

mod arena;

use core::str::FromStr;

use bip388::{ClearText, DescriptorTemplate};

/// Maximum confusion score for which a cleartext description should be shown
/// instead of the raw descriptor. Mirrors `bip388::MAX_CONFUSION_SCORE`. The
/// binding always returns the raw score; applying this gate is the caller's
/// responsibility (matching the Rust contract).
///
/// A literal (not the cross-crate path) so cbindgen can emit it; the
/// compile-time assert below keeps it in lock-step with the source of truth.
pub const BIP388_MAX_CONFUSION_SCORE: u64 = 100_000;
const _: () = assert!(BIP388_MAX_CONFUSION_SCORE == bip388::MAX_CONFUSION_SCORE);

/// Largest taptree leaf count the binding will process (Ledger app limit).
pub const BIP388_MAX_TAPLEAVES: usize = 8;

/// Hard cap on descriptor length; anything longer is rejected as
/// [`Bip388Status::PolicyTooComplex`] regardless of arena size.
pub const BIP388_MAX_DESCRIPTOR_LEN: usize = 1024;

/// Arena size that holds every policy within the Ledger app's limits (<=15 keys
/// total, <=8 leaves) with margin; a good default for callers that don't size
/// the arena per descriptor via [`bip388_min_arena_size`]. Realistic policies
/// fit in far less (a single-sig needs well under 2 KiB).
pub const BIP388_RECOMMENDED_ARENA_SIZE: usize = 8 * 1024;

// --- arena-fit model -------------------------------------------------------
//
// Peak working-set bytes are dominated by the descriptor AST and rendered
// output. Empirically (against the real reclaiming allocator, fragmentation
// included) the peak is bounded by an affine function of three cheap-to-measure
// quantities: key-placeholder occurrences (`@`), taptree branch nodes (`{`,
// which add per-leaf overhead), and descriptor length (e.g. hash fragments).
// These constants are a *safe upper bound* validated across worst-case shapes
// against the real allocator by `examples/calibrate.c` (>= ~17% margin); they
// intentionally over-estimate so the a priori check never under-provisions —
// under-provisioning would let an infallible allocation fail and abort, which
// is exactly what we avoid. Re-run the calibration tool if `bip388`'s parser or
// renderer changes.
const ARENA_BASE: usize = 2048;
const ARENA_PER_OCCURRENCE: usize = 112;
const ARENA_PER_BRANCH: usize = 192;
const ARENA_PER_BYTE: usize = 2;

/// Upper bound on the arena bytes needed to process a descriptor with the given
/// number of key-placeholder occurrences, taptree branch nodes, and byte length.
pub fn required_arena_bytes(occurrences: usize, branches: usize, len: usize) -> usize {
    ARENA_BASE
        .saturating_add(ARENA_PER_OCCURRENCE.saturating_mul(occurrences))
        .saturating_add(ARENA_PER_BRANCH.saturating_mul(branches))
        .saturating_add(ARENA_PER_BYTE.saturating_mul(len))
}

/// Result code returned by every entry point. `Ok` is zero; all errors negative.
#[repr(i32)]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Bip388Status {
    /// Success.
    Ok = 0,
    /// A required pointer argument was null.
    NullArg = -1,
    /// `descriptor[..descriptor_len]` was not valid UTF-8.
    InvalidUtf8 = -2,
    /// The descriptor template failed to parse (`bip388::ParseError`).
    ParseError = -3,
    /// The `out` byte buffer was too small to hold the rendered text.
    BufferTooSmall = -4,
    /// The `lines` array could not hold all produced lines.
    TooManyLines = -5,
    /// The supplied arena is too small for this descriptor. Provide at least
    /// [`bip388_min_arena_size`] bytes (no allocation was attempted).
    OutOfArena = -6,
    /// The descriptor is structurally out of the supported range (too long, or
    /// more than [`BIP388_MAX_TAPLEAVES`] taptree leaves).
    PolicyTooComplex = -7,
}

/// One rendered cleartext line: a UTF-8 slice (NOT NUL-terminated) pointing into
/// the caller's `out` buffer, valid until that buffer is reused.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct Bip388Line {
    /// Pointer into the caller `out` buffer.
    pub ptr: *const u8,
    /// Length of the line in bytes.
    pub len: usize,
}

/// Cheap O(n) scan of the raw descriptor bytes (no allocation).
struct Scan {
    len: usize,
    occurrences: usize,
    branches: usize,
}

fn prescan(bytes: &[u8]) -> Scan {
    let mut occurrences = 0;
    let mut branches = 0;
    for &b in bytes {
        match b {
            b'@' => occurrences += 1,
            b'{' => branches += 1,
            _ => {}
        }
    }
    Scan {
        len: bytes.len(),
        occurrences,
        branches,
    }
}

impl Scan {
    /// Returns the structural-range / arena-fit verdict, or `Ok` if the
    /// descriptor may be processed within `arena_len` bytes.
    fn check(&self, arena_len: usize) -> Bip388Status {
        if self.len > BIP388_MAX_DESCRIPTOR_LEN {
            return Bip388Status::PolicyTooComplex;
        }
        // A full binary taptree with L leaves has L-1 branch nodes (`{`), so
        // `branches + 1` leaves. Reject more than BIP388_MAX_TAPLEAVES.
        if self.branches + 1 > BIP388_MAX_TAPLEAVES {
            return Bip388Status::PolicyTooComplex;
        }
        if arena_len < required_arena_bytes(self.occurrences, self.branches, self.len) {
            return Bip388Status::OutOfArena;
        }
        Bip388Status::Ok
    }
}

/// RAII guard: detaches the arena on any return path. No-op under `std`.
struct ArenaGuard;
impl Drop for ArenaGuard {
    fn drop(&mut self) {
        #[cfg(not(feature = "std"))]
        unsafe {
            arena::clear();
        }
    }
}

/// Installs the caller arena (no_std) and returns a guard that clears it on drop.
///
/// # Safety
/// `arena[..arena_len]` must be writable and valid for the call's duration.
unsafe fn enter_arena(_arena: *mut u8, _arena_len: usize) -> ArenaGuard {
    #[cfg(not(feature = "std"))]
    arena::install(_arena, _arena_len);
    ArenaGuard
}

/// Parses `descriptor[..descriptor_len]` into a `DescriptorTemplate`.
fn parse(descriptor: *const u8, descriptor_len: usize) -> Result<DescriptorTemplate, Bip388Status> {
    // SAFETY: caller guarantees `descriptor[..descriptor_len]` is readable.
    let bytes = unsafe { core::slice::from_raw_parts(descriptor, descriptor_len) };
    let text = core::str::from_utf8(bytes).map_err(|_| Bip388Status::InvalidUtf8)?;
    DescriptorTemplate::from_str(text).map_err(|_| Bip388Status::ParseError)
}

/// Shared entry guard: null-checks `descriptor`/`arena`, pre-scans, and applies
/// the structural / arena-fit check. On `Ok`, the arena is installed and the
/// returned guard detaches it on drop.
unsafe fn begin(
    descriptor: *const u8,
    descriptor_len: usize,
    arena: *mut u8,
    arena_len: usize,
) -> Result<ArenaGuard, Bip388Status> {
    if descriptor.is_null() {
        return Err(Bip388Status::NullArg);
    }
    #[cfg(not(feature = "std"))]
    if arena.is_null() || arena_len == 0 {
        return Err(Bip388Status::NullArg);
    }
    let bytes = core::slice::from_raw_parts(descriptor, descriptor_len);
    match prescan(bytes).check(arena_len) {
        Bip388Status::Ok => Ok(enter_arena(arena, arena_len)),
        other => Err(other),
    }
}

/// Parses `descriptor` and writes its confusion score (an upper bound on the
/// number of descriptor templates sharing the same cleartext) to
/// `confusion_score_out`.
///
/// `arena[..arena_len]` is scratch memory used internally and is detached before
/// returning. Returns [`Bip388Status::Ok`] on success.
///
/// # Safety
/// All non-null pointers must reference valid memory of the stated sizes; the
/// binding is single-threaded.
#[no_mangle]
pub unsafe extern "C" fn bip388_confusion_score(
    descriptor: *const u8,
    descriptor_len: usize,
    arena: *mut u8,
    arena_len: usize,
    confusion_score_out: *mut u64,
) -> Bip388Status {
    if confusion_score_out.is_null() {
        return Bip388Status::NullArg;
    }
    let _guard = match begin(descriptor, descriptor_len, arena, arena_len) {
        Ok(g) => g,
        Err(s) => return s,
    };

    let template = match parse(descriptor, descriptor_len) {
        Ok(t) => t,
        Err(s) => return s,
    };
    confusion_score_out.write(template.confusion_score());
    Bip388Status::Ok
}

/// Parses `descriptor`, renders its cleartext lines, and reports the confusion
/// score and whether every part has a cleartext rendering.
///
/// For taproot descriptors the first line describes the key-path policy and the
/// remaining lines describe the leaves (in canonical display order). A part
/// without a cleartext rendering is emitted as the raw descriptor template and
/// `has_cleartext_out` is set to `false`.
///
/// Memory model (caller owns everything):
/// - `arena[..arena_len]`: internal scratch, detached before returning.
/// - `out[..out_len]`: storage the line bytes are copied into.
/// - `lines[..lines_cap]`: array filled with `(ptr,len)` slices into `out`.
///
/// Outputs `n_lines_out`, `has_cleartext_out`, `confusion_score_out`.
///
/// # Safety
/// All non-null pointers must reference valid memory of the stated sizes; the
/// binding is single-threaded. The `lines` slices stay valid until `out` is
/// reused.
#[no_mangle]
pub unsafe extern "C" fn bip388_to_cleartext(
    descriptor: *const u8,
    descriptor_len: usize,
    arena: *mut u8,
    arena_len: usize,
    out: *mut u8,
    out_len: usize,
    lines: *mut Bip388Line,
    lines_cap: usize,
    n_lines_out: *mut usize,
    has_cleartext_out: *mut bool,
    confusion_score_out: *mut u64,
) -> Bip388Status {
    if out.is_null()
        || lines.is_null()
        || n_lines_out.is_null()
        || has_cleartext_out.is_null()
        || confusion_score_out.is_null()
    {
        return Bip388Status::NullArg;
    }
    let _guard = match begin(descriptor, descriptor_len, arena, arena_len) {
        Ok(g) => g,
        Err(s) => return s,
    };

    let template = match parse(descriptor, descriptor_len) {
        Ok(t) => t,
        Err(s) => return s,
    };

    let score = template.confusion_score();
    let (descriptions, has_cleartext) = template.to_cleartext();

    if descriptions.len() > lines_cap {
        return Bip388Status::TooManyLines;
    }

    // Copy each line contiguously into `out`, recording a slice descriptor that
    // points into `out` (NOT into the arena, which is detached on return).
    let mut offset: usize = 0;
    for (i, line) in descriptions.iter().enumerate() {
        let bytes = line.as_bytes();
        let end = match offset.checked_add(bytes.len()) {
            Some(e) if e <= out_len => e,
            _ => return Bip388Status::BufferTooSmall,
        };
        let dst = out.add(offset);
        core::ptr::copy_nonoverlapping(bytes.as_ptr(), dst, bytes.len());
        lines.add(i).write(Bip388Line {
            ptr: dst as *const u8,
            len: bytes.len(),
        });
        offset = end;
    }

    n_lines_out.write(descriptions.len());
    has_cleartext_out.write(has_cleartext);
    confusion_score_out.write(score);
    Bip388Status::Ok
}

/// Writes to `min_arena_out` the minimum arena size (bytes) required to process
/// `descriptor`, without allocating. A caller may use this to size the arena
/// exactly, or compare against a fixed buffer. Returns `PolicyTooComplex` if the
/// descriptor is structurally out of range, else `Ok`.
///
/// # Safety
/// `descriptor[..descriptor_len]` and `min_arena_out` must be valid.
#[no_mangle]
pub unsafe extern "C" fn bip388_min_arena_size(
    descriptor: *const u8,
    descriptor_len: usize,
    min_arena_out: *mut usize,
) -> Bip388Status {
    if descriptor.is_null() || min_arena_out.is_null() {
        return Bip388Status::NullArg;
    }
    let bytes = core::slice::from_raw_parts(descriptor, descriptor_len);
    let scan = prescan(bytes);
    if scan.len > BIP388_MAX_DESCRIPTOR_LEN || scan.branches + 1 > BIP388_MAX_TAPLEAVES {
        return Bip388Status::PolicyTooComplex;
    }
    min_arena_out.write(required_arena_bytes(scan.occurrences, scan.branches, scan.len));
    Bip388Status::Ok
}

/// Debug aid: peak arena bytes used by the most recent call (real allocator,
/// fragmentation included). Returns 0 under the `std` build. Used to validate
/// the arena-fit model; not part of the stable contract.
#[no_mangle]
pub extern "C" fn bip388_debug_peak_used() -> usize {
    #[cfg(not(feature = "std"))]
    {
        arena::peak_used()
    }
    #[cfg(feature = "std")]
    {
        0
    }
}

/// Freestanding `no_std` panic handler. The FFI path returns errors via `Result`
/// and never relies on unwinding; this only guards the unreachable case.
#[cfg(not(feature = "std"))]
#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! {
    extern "C" {
        fn abort() -> !;
    }
    unsafe { abort() }
}

#[cfg(test)]
mod tests;
