/*
 * C bindings for the bip388 cleartext API. Generated by cbindgen — do not edit.
 *
 * Memory model: the caller provides ALL memory. `arena` is scratch the Rust
 * internals bump-allocate from for the duration of one call and is detached
 * before returning; `out` holds the rendered line bytes; `lines` receives
 * (ptr,len) slices into `out`. Nothing Rust-owned escapes, so there is nothing
 * to free. The binding is single-threaded. A `Bip388Line` is UTF-8 and is NOT
 * NUL-terminated; it stays valid until `out` is reused.
 *
 * Size `arena` per BIP388_RECOMMENDED_ARENA_SIZE; a genuine arena overflow
 * aborts cleanly (a trap) rather than returning a partial result.
 */


#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Maximum confusion score for which a cleartext description should be shown
// instead of the raw descriptor. Mirrors `bip388::MAX_CONFUSION_SCORE`. The
// binding always returns the raw score; applying this gate is the caller's
// responsibility (matching the Rust contract).
//
// A literal (not the cross-crate path) so cbindgen can emit it; the
// compile-time assert below keeps it in lock-step with the source of truth.
#define BIP388_MAX_CONFUSION_SCORE 100000

// Largest taptree leaf count the binding will process (Ledger app limit).
#define BIP388_MAX_TAPLEAVES 8

// Hard cap on descriptor length; anything longer is rejected as
// [`Bip388Status::PolicyTooComplex`] regardless of arena size.
#define BIP388_MAX_DESCRIPTOR_LEN 1024

// Arena size that holds every policy within the Ledger app's limits (<=15 keys
// total, <=8 leaves) with margin; a good default for callers that don't size
// the arena per descriptor via [`bip388_min_arena_size`]. Realistic policies
// fit in far less (a single-sig needs well under 2 KiB).
#define BIP388_RECOMMENDED_ARENA_SIZE (8 * 1024)

// Result code returned by every entry point. `Ok` is zero; all errors negative.
enum Bip388Status
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
    // Success.
    BIP388_STATUS_OK = 0,
    // A required pointer argument was null.
    BIP388_STATUS_NULL_ARG = -1,
    // `descriptor[..descriptor_len]` was not valid UTF-8.
    BIP388_STATUS_INVALID_UTF8 = -2,
    // The descriptor template failed to parse (`bip388::ParseError`).
    BIP388_STATUS_PARSE_ERROR = -3,
    // The `out` byte buffer was too small to hold the rendered text.
    BIP388_STATUS_BUFFER_TOO_SMALL = -4,
    // The `lines` array could not hold all produced lines.
    BIP388_STATUS_TOO_MANY_LINES = -5,
    // The supplied arena is too small for this descriptor. Provide at least
    // [`bip388_min_arena_size`] bytes (no allocation was attempted).
    BIP388_STATUS_OUT_OF_ARENA = -6,
    // The descriptor is structurally out of the supported range (too long, or
    // more than [`BIP388_MAX_TAPLEAVES`] taptree leaves).
    BIP388_STATUS_POLICY_TOO_COMPLEX = -7,
};
#ifndef __cplusplus
typedef int32_t Bip388Status;
#endif // __cplusplus

// One rendered cleartext line: a UTF-8 slice (NOT NUL-terminated) pointing into
// the caller's `out` buffer, valid until that buffer is reused.
typedef struct Bip388Line {
    // Pointer into the caller `out` buffer.
    const uint8_t *ptr;
    // Length of the line in bytes.
    uintptr_t len;
} Bip388Line;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Parses `descriptor` and writes its confusion score (an upper bound on the
// number of descriptor templates sharing the same cleartext) to
// `confusion_score_out`.
//
// `arena[..arena_len]` is scratch memory used internally and is detached before
// returning. Returns [`Bip388Status::Ok`] on success.
//
// # Safety
// All non-null pointers must reference valid memory of the stated sizes; the
// binding is single-threaded.
Bip388Status bip388_confusion_score(const uint8_t *descriptor,
                                    uintptr_t descriptor_len,
                                    uint8_t *arena,
                                    uintptr_t arena_len,
                                    uint64_t *confusion_score_out);

// Parses `descriptor`, renders its cleartext lines, and reports the confusion
// score and whether every part has a cleartext rendering.
//
// For taproot descriptors the first line describes the key-path policy and the
// remaining lines describe the leaves (in canonical display order). A part
// without a cleartext rendering is emitted as the raw descriptor template and
// `has_cleartext_out` is set to `false`.
//
// Memory model (caller owns everything):
// - `arena[..arena_len]`: internal scratch, detached before returning.
// - `out[..out_len]`: storage the line bytes are copied into.
// - `lines[..lines_cap]`: array filled with `(ptr,len)` slices into `out`.
//
// Outputs `n_lines_out`, `has_cleartext_out`, `confusion_score_out`.
//
// # Safety
// All non-null pointers must reference valid memory of the stated sizes; the
// binding is single-threaded. The `lines` slices stay valid until `out` is
// reused.
Bip388Status bip388_to_cleartext(const uint8_t *descriptor,
                                 uintptr_t descriptor_len,
                                 uint8_t *arena,
                                 uintptr_t arena_len,
                                 uint8_t *out,
                                 uintptr_t out_len,
                                 struct Bip388Line *lines,
                                 uintptr_t lines_cap,
                                 uintptr_t *n_lines_out,
                                 bool *has_cleartext_out,
                                 uint64_t *confusion_score_out);

// Writes to `min_arena_out` the minimum arena size (bytes) required to process
// `descriptor`, without allocating. A caller may use this to size the arena
// exactly, or compare against a fixed buffer. Returns `PolicyTooComplex` if the
// descriptor is structurally out of range, else `Ok`.
//
// # Safety
// `descriptor[..descriptor_len]` and `min_arena_out` must be valid.
Bip388Status bip388_min_arena_size(const uint8_t *descriptor,
                                   uintptr_t descriptor_len,
                                   uintptr_t *min_arena_out);

// Debug aid: peak arena bytes used by the most recent call (real allocator,
// fragmentation included). Returns 0 under the `std` build. Used to validate
// the arena-fit model; not part of the stable contract.
uintptr_t bip388_debug_peak_used(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
