#ifndef _BTCHIP_APDU_GET_WALLET_PUBLIC_KEY_H_
#define _BTCHIP_APDU_GET_WALLET_PUBLIC_KEY_H_

#define P1_NO_DISPLAY 0x00
#define P1_DISPLAY 0x01
#define P1_REQUEST_TOKEN 0x02

#define P2_LEGACY 0x00
#define P2_SEGWIT 0x01
#define P2_NATIVE_SEGWIT 0x02
#define P2_CASHADDR 0x03

#endif //_BTCHIP_APDU_GET_WALLET_PUBLIC_KEY_H_