// Generated by dev-tools/gen_cleartext/gen.py. DO NOT EDIT.
// clang-format off

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// A part of a cleartext template. Literals reference ct_string_pool
// at `lit_off`; dynamic placeholders refer to the binding at index
// `binding_idx` in the matcher's bindings array.
typedef enum {
    CT_PART_LITERAL = 0,
    CT_PART_KEY,
    CT_PART_KEYS,
    CT_PART_THRESHOLD,
    CT_PART_SUB,
    CT_PART_TIMELOCK,
} cleartext_part_kind_e;

typedef struct {
    uint8_t  kind;         // cleartext_part_kind_e
    uint8_t  binding_idx;  // ignored for CT_PART_LITERAL
    uint16_t lit_off;      // valid only for CT_PART_LITERAL
} cleartext_part_t;

typedef struct {
    uint8_t n_patterns;        // total patterns for the class
    uint8_t n_musig_patterns;  // patterns whose admittance requires
                               //   threshold == n_keys
    uint8_t n_parts;
    const cleartext_part_t *parts;
} cleartext_spec_t;

typedef enum {
    DC_LEGACY_SINGLE_SIG,
    DC_SEGWIT_SINGLE_SIG,
    DC_SEGWIT_MULTISIG,
    DC_TAPROOT,
    DC_TAPROOT_MUSIG,
    DC_OTHER,
    DC__COUNT = DC_OTHER,
} descriptor_class_e;

typedef enum {
    TC_SINGLE_SIG,
    TC_BOTH_MUST_SIGN,
    TC_SORTED_MULTISIG,
    TC_MULTISIG,
    TC_TIMELOCKED,
    TC_AND_V,
    TC_OTHER,
    TC__COUNT = TC_OTHER,
} tapleaf_class_e;

extern const char ct_string_pool[];
extern const cleartext_spec_t CT_TOP_LEVEL_SPECS[DC__COUNT];
extern const cleartext_spec_t CT_TAPLEAF_SPECS[TC__COUNT];

