// Generated by specs/bip388/gen.py. DO NOT EDIT.
// clang-format off

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// A part of a cleartext template. Literals reference ct_string_pool
// at `lit_off`; dynamic placeholders refer to the binding at index
// `binding_idx` in the matcher's bindings array.
typedef enum {
    CT_PART_LITERAL = 0,
    CT_PART_KEY,
    CT_PART_KEYS,
    CT_PART_THRESHOLD,
    CT_PART_SUB,
    CT_PART_TIMELOCK,
} cleartext_part_kind_e;

typedef struct {
    uint8_t  kind;         // cleartext_part_kind_e
    uint8_t  binding_idx;  // ignored for CT_PART_LITERAL
    uint16_t lit_off;      // valid only for CT_PART_LITERAL
} cleartext_part_t;

typedef struct {
    uint8_t n_patterns;        // total patterns for the class
    uint8_t n_musig_patterns;  // patterns whose admittance requires
                               //   threshold == n_keys
    uint8_t n_parts;
    const cleartext_part_t *parts;
    uint8_t n_parts_all;               // 0 if the class has no n-of-n form
    const cleartext_part_t *parts_all; // alternate template used when
                                       //   threshold == n_keys; NULL if absent
    uint8_t recurses;                  // 1 iff the class binds a $leaves
                                       //   taptree (drives per-leaf
                                       //   rendering and the taptree score)
} cleartext_spec_t;

// Classes of the *root* of a wallet-policy descriptor template. Each named
// value (the sentinels aside) is one shape the cleartext encoder recognizes,
// listed in the same order as the `[[top_level]]` entries of
// specs/bip388/cleartext.toml (the single source of truth for their meaning).
// match_top_level() in cleartext.c yields one of these, and it indexes
// CT_TOP_LEVEL_SPECS[] to select that shape's cleartext rendering.
//   DC_OTHER  - matches no known shape: no cleartext form, so the UX falls
//               back to showing the raw descriptor template.
//   DC__COUNT - number of recognized classes (== DC_OTHER); sizes
//               CT_TOP_LEVEL_SPECS[], which has no entry for DC_OTHER.
typedef enum {
    DC_LEGACY_SINGLE_SIG,
    DC_SEGWIT_SINGLE_SIG,
    DC_MULTISIG,
    DC_TAPROOT_KEY_ONLY,
    DC_TAPROOT,
    DC_TAPROOT_MUSIG,
    DC_OTHER,
    DC__COUNT = DC_OTHER,
} descriptor_class_e;

// Classes of a single leaf script of a taproot tree. Each named value (the
// sentinels aside) is one leaf shape the cleartext encoder recognizes, listed
// in the same order as the `[[tapleaf]]` entries of
// specs/bip388/cleartext.toml (the single source of truth for their meaning).
// match_tapleaf() in cleartext.c yields one of these, and it indexes
// CT_TAPLEAF_SPECS[] to select that leaf's cleartext rendering.
//   TC_OTHER  - matches no known shape: no cleartext form, so the leaf is
//               rendered as the fixed "(unknown)" marker.
//   TC__COUNT - number of recognized classes (== TC_OTHER); sizes
//               CT_TAPLEAF_SPECS[], which has no entry for TC_OTHER.
typedef enum {
    TC_SINGLE_SIG,
    TC_BOTH_MUST_SIGN,
    TC_SORTED_MULTISIG,
    TC_MULTISIG,
    TC_TIMELOCKED,
    TC_AND_V,
    TC_OTHER,
    TC__COUNT = TC_OTHER,
} tapleaf_class_e;

extern const char ct_string_pool[];
extern const cleartext_spec_t CT_TOP_LEVEL_SPECS[DC__COUNT];
extern const cleartext_spec_t CT_TAPLEAF_SPECS[TC__COUNT];

