// Generated by specs/bip388/gen.py. DO NOT EDIT.
// clang-format off

#include "common/cleartext_match.h"

// Classifier for the root descriptor template. Mirrors the `[[top_level]]`
// patterns of specs/bip388/cleartext.toml, tried in order.
bool match_top_level(const policy_node_t *root, ct_top_match_t *out) {
    out->cls = DC_OTHER;
    out->bindings.n = 0;
    out->taptree = NULL;
    if (root == NULL) return false;

    // LegacySingleSig: pkh($key)
    do {
        if (root == NULL || root->type != TOKEN_PKH) break;
        const policy_node_with_key_t *ct_n1 = (const policy_node_with_key_t *) root;
        const policy_node_keyexpr_t *ct_k2 = ct_n1->key;
        if (ct_k2->type != KEY_EXPRESSION_NORMAL) break;
        set_binding_key(&out->bindings, 0, ct_k2);
        out->bindings.n = 1;
        out->cls = DC_LEGACY_SINGLE_SIG;
        return true;
    } while (0);

    // SegwitSingleSig: wpkh($key)
    do {
        if (root == NULL || root->type != TOKEN_WPKH) break;
        const policy_node_with_key_t *ct_n1 = (const policy_node_with_key_t *) root;
        const policy_node_keyexpr_t *ct_k2 = ct_n1->key;
        if (ct_k2->type != KEY_EXPRESSION_NORMAL) break;
        set_binding_key(&out->bindings, 0, ct_k2);
        out->bindings.n = 1;
        out->cls = DC_SEGWIT_SINGLE_SIG;
        return true;
    } while (0);
    // SegwitSingleSig: sh(wpkh($key))
    do {
        if (root == NULL || root->type != TOKEN_SH) break;
        const policy_node_with_script_t *ct_n1 = (const policy_node_with_script_t *) root;
        const policy_node_t *ct_c2 = ct_n1->script;
        if (ct_c2 == NULL || ct_c2->type != TOKEN_WPKH) break;
        const policy_node_with_key_t *ct_n3 = (const policy_node_with_key_t *) ct_c2;
        const policy_node_keyexpr_t *ct_k4 = ct_n3->key;
        if (ct_k4->type != KEY_EXPRESSION_NORMAL) break;
        set_binding_key(&out->bindings, 0, ct_k4);
        out->bindings.n = 1;
        out->cls = DC_SEGWIT_SINGLE_SIG;
        return true;
    } while (0);

    // Multisig: sh(multi($threshold, $keys))
    do {
        if (root == NULL || root->type != TOKEN_SH) break;
        const policy_node_with_script_t *ct_n1 = (const policy_node_with_script_t *) root;
        const policy_node_t *ct_c2 = ct_n1->script;
        if (ct_c2 == NULL || ct_c2->type != TOKEN_MULTI) break;
        const policy_node_multisig_t *ct_n3 = (const policy_node_multisig_t *) ct_c2;
        const policy_node_keyexpr_t *ct_ka4 = ct_n3->keys;
        set_binding_number(&out->bindings, 0, ct_n3->k);
        set_binding_keys(&out->bindings, 1, ct_ka4, ct_n3->n);
        out->bindings.n = 2;
        out->cls = DC_MULTISIG;
        return true;
    } while (0);
    // Multisig: sh(sortedmulti($threshold, $keys))
    do {
        if (root == NULL || root->type != TOKEN_SH) break;
        const policy_node_with_script_t *ct_n1 = (const policy_node_with_script_t *) root;
        const policy_node_t *ct_c2 = ct_n1->script;
        if (ct_c2 == NULL || ct_c2->type != TOKEN_SORTEDMULTI) break;
        const policy_node_multisig_t *ct_n3 = (const policy_node_multisig_t *) ct_c2;
        const policy_node_keyexpr_t *ct_ka4 = ct_n3->keys;
        set_binding_number(&out->bindings, 0, ct_n3->k);
        set_binding_keys(&out->bindings, 1, ct_ka4, ct_n3->n);
        out->bindings.n = 2;
        out->cls = DC_MULTISIG;
        return true;
    } while (0);
    // Multisig: wsh(multi($threshold, $keys))
    do {
        if (root == NULL || root->type != TOKEN_WSH) break;
        const policy_node_with_script_t *ct_n1 = (const policy_node_with_script_t *) root;
        const policy_node_t *ct_c2 = ct_n1->script;
        if (ct_c2 == NULL || ct_c2->type != TOKEN_MULTI) break;
        const policy_node_multisig_t *ct_n3 = (const policy_node_multisig_t *) ct_c2;
        const policy_node_keyexpr_t *ct_ka4 = ct_n3->keys;
        set_binding_number(&out->bindings, 0, ct_n3->k);
        set_binding_keys(&out->bindings, 1, ct_ka4, ct_n3->n);
        out->bindings.n = 2;
        out->cls = DC_MULTISIG;
        return true;
    } while (0);
    // Multisig: wsh(sortedmulti($threshold, $keys))
    do {
        if (root == NULL || root->type != TOKEN_WSH) break;
        const policy_node_with_script_t *ct_n1 = (const policy_node_with_script_t *) root;
        const policy_node_t *ct_c2 = ct_n1->script;
        if (ct_c2 == NULL || ct_c2->type != TOKEN_SORTEDMULTI) break;
        const policy_node_multisig_t *ct_n3 = (const policy_node_multisig_t *) ct_c2;
        const policy_node_keyexpr_t *ct_ka4 = ct_n3->keys;
        set_binding_number(&out->bindings, 0, ct_n3->k);
        set_binding_keys(&out->bindings, 1, ct_ka4, ct_n3->n);
        out->bindings.n = 2;
        out->cls = DC_MULTISIG;
        return true;
    } while (0);
    // Multisig: sh(wsh(multi($threshold, $keys)))
    do {
        if (root == NULL || root->type != TOKEN_SH) break;
        const policy_node_with_script_t *ct_n1 = (const policy_node_with_script_t *) root;
        const policy_node_t *ct_c2 = ct_n1->script;
        if (ct_c2 == NULL || ct_c2->type != TOKEN_WSH) break;
        const policy_node_with_script_t *ct_n3 = (const policy_node_with_script_t *) ct_c2;
        const policy_node_t *ct_c4 = ct_n3->script;
        if (ct_c4 == NULL || ct_c4->type != TOKEN_MULTI) break;
        const policy_node_multisig_t *ct_n5 = (const policy_node_multisig_t *) ct_c4;
        const policy_node_keyexpr_t *ct_ka6 = ct_n5->keys;
        set_binding_number(&out->bindings, 0, ct_n5->k);
        set_binding_keys(&out->bindings, 1, ct_ka6, ct_n5->n);
        out->bindings.n = 2;
        out->cls = DC_MULTISIG;
        return true;
    } while (0);
    // Multisig: sh(wsh(sortedmulti($threshold, $keys)))
    do {
        if (root == NULL || root->type != TOKEN_SH) break;
        const policy_node_with_script_t *ct_n1 = (const policy_node_with_script_t *) root;
        const policy_node_t *ct_c2 = ct_n1->script;
        if (ct_c2 == NULL || ct_c2->type != TOKEN_WSH) break;
        const policy_node_with_script_t *ct_n3 = (const policy_node_with_script_t *) ct_c2;
        const policy_node_t *ct_c4 = ct_n3->script;
        if (ct_c4 == NULL || ct_c4->type != TOKEN_SORTEDMULTI) break;
        const policy_node_multisig_t *ct_n5 = (const policy_node_multisig_t *) ct_c4;
        const policy_node_keyexpr_t *ct_ka6 = ct_n5->keys;
        set_binding_number(&out->bindings, 0, ct_n5->k);
        set_binding_keys(&out->bindings, 1, ct_ka6, ct_n5->n);
        out->bindings.n = 2;
        out->cls = DC_MULTISIG;
        return true;
    } while (0);
    // Multisig: tr(musig($keys))
    do {
        if (root == NULL || root->type != TOKEN_TR) break;
        const policy_node_tr_t *ct_n1 = (const policy_node_tr_t *) root;
        const policy_node_keyexpr_t *ct_k2 = ct_n1->key;
        if (ct_k2->type != KEY_EXPRESSION_MUSIG) break;
        const musig_aggr_key_info_t *ct_mi3 = ct_k2->m.musig_info;
        if (ct_n1->tree != NULL) break;
        set_binding_number(&out->bindings, 0, ct_mi3->n);
        set_binding_keys(&out->bindings, 1, ct_k2, 1);
        out->bindings.n = 2;
        out->cls = DC_MULTISIG;
        return true;
    } while (0);

    // TaprootKeyOnly: tr($internal_key)
    do {
        if (root == NULL || root->type != TOKEN_TR) break;
        const policy_node_tr_t *ct_n1 = (const policy_node_tr_t *) root;
        const policy_node_keyexpr_t *ct_k2 = ct_n1->key;
        if (ct_k2->type != KEY_EXPRESSION_NORMAL) break;
        if (ct_n1->tree != NULL) break;
        set_binding_key(&out->bindings, 0, ct_k2);
        out->bindings.n = 1;
        out->cls = DC_TAPROOT_KEY_ONLY;
        return true;
    } while (0);

    // Taproot: tr($internal_key, $leaves)
    do {
        if (root == NULL || root->type != TOKEN_TR) break;
        const policy_node_tr_t *ct_n1 = (const policy_node_tr_t *) root;
        const policy_node_keyexpr_t *ct_k2 = ct_n1->key;
        if (ct_k2->type != KEY_EXPRESSION_NORMAL) break;
        if (ct_n1->tree == NULL) break;
        set_binding_key(&out->bindings, 0, ct_k2);
        out->taptree = ct_n1->tree;
        out->bindings.n = 1;
        out->cls = DC_TAPROOT;
        return true;
    } while (0);

    // TaprootMusig: tr(musig($keys), $leaves)
    do {
        if (root == NULL || root->type != TOKEN_TR) break;
        const policy_node_tr_t *ct_n1 = (const policy_node_tr_t *) root;
        const policy_node_keyexpr_t *ct_k2 = ct_n1->key;
        if (ct_k2->type != KEY_EXPRESSION_MUSIG) break;
        const musig_aggr_key_info_t *ct_mi3 = ct_k2->m.musig_info;
        if (ct_n1->tree == NULL) break;
        set_binding_number(&out->bindings, 0, ct_mi3->n);
        set_binding_keys(&out->bindings, 1, ct_k2, 1);
        out->taptree = ct_n1->tree;
        out->bindings.n = 2;
        out->cls = DC_TAPROOT_MUSIG;
        return true;
    } while (0);

    return false;
}

// Classifier for a single tap-leaf script. Mirrors the `[[tapleaf]]`
// patterns of specs/bip388/cleartext.toml, tried in order.
bool match_tapleaf(const policy_node_t *leaf_script, ct_leaf_match_t *out) {
    out->cls = TC_OTHER;
    out->bindings.n = 0;
    out->leaf_script = leaf_script;
    if (leaf_script == NULL) return false;

    // SingleSig: pk($key)
    do {
        if (leaf_script == NULL || leaf_script->type != TOKEN_PK) break;
        const policy_node_with_key_t *ct_n1 = (const policy_node_with_key_t *) leaf_script;
        const policy_node_keyexpr_t *ct_k2 = ct_n1->key;
        if (ct_k2->type != KEY_EXPRESSION_NORMAL) break;
        set_binding_key(&out->bindings, 0, ct_k2);
        out->bindings.n = 1;
        out->cls = TC_SINGLE_SIG;
        return true;
    } while (0);

    // BothMustSign: and_v(v:pk($key1), pk($key2))
    do {
        if (leaf_script == NULL || leaf_script->type != TOKEN_AND_V) break;
        const policy_node_with_script2_t *ct_n1 = (const policy_node_with_script2_t *) leaf_script;
        const policy_node_t *ct_c2 = ct_n1->scripts[0];
        if (ct_c2 == NULL || ct_c2->type != TOKEN_V) break;
        const policy_node_with_script_t *ct_w3 = (const policy_node_with_script_t *) ct_c2;
        const policy_node_t *ct_c4 = ct_w3->script;
        if (ct_c4 == NULL || ct_c4->type != TOKEN_PK) break;
        const policy_node_with_key_t *ct_n5 = (const policy_node_with_key_t *) ct_c4;
        const policy_node_keyexpr_t *ct_k6 = ct_n5->key;
        if (ct_k6->type != KEY_EXPRESSION_NORMAL) break;
        const policy_node_t *ct_c7 = ct_n1->scripts[1];
        if (ct_c7 == NULL || ct_c7->type != TOKEN_PK) break;
        const policy_node_with_key_t *ct_n8 = (const policy_node_with_key_t *) ct_c7;
        const policy_node_keyexpr_t *ct_k9 = ct_n8->key;
        if (ct_k9->type != KEY_EXPRESSION_NORMAL) break;
        set_binding_key(&out->bindings, 0, ct_k6);
        set_binding_key(&out->bindings, 1, ct_k9);
        out->bindings.n = 2;
        out->cls = TC_BOTH_MUST_SIGN;
        return true;
    } while (0);

    // SortedMultisig: sortedmulti_a($threshold, $keys)
    do {
        if (leaf_script == NULL || leaf_script->type != TOKEN_SORTEDMULTI_A) break;
        const policy_node_multisig_t *ct_n1 = (const policy_node_multisig_t *) leaf_script;
        const policy_node_keyexpr_t *ct_ka2 = ct_n1->keys;
        set_binding_number(&out->bindings, 0, ct_n1->k);
        set_binding_keys(&out->bindings, 1, ct_ka2, ct_n1->n);
        out->bindings.n = 2;
        out->cls = TC_SORTED_MULTISIG;
        return true;
    } while (0);

    // Multisig: multi_a($threshold, $keys)
    do {
        if (leaf_script == NULL || leaf_script->type != TOKEN_MULTI_A) break;
        const policy_node_multisig_t *ct_n1 = (const policy_node_multisig_t *) leaf_script;
        const policy_node_keyexpr_t *ct_ka2 = ct_n1->keys;
        set_binding_number(&out->bindings, 0, ct_n1->k);
        set_binding_keys(&out->bindings, 1, ct_ka2, ct_n1->n);
        out->bindings.n = 2;
        out->cls = TC_MULTISIG;
        return true;
    } while (0);
    // Multisig: pk(musig($keys))
    do {
        if (leaf_script == NULL || leaf_script->type != TOKEN_PK) break;
        const policy_node_with_key_t *ct_n1 = (const policy_node_with_key_t *) leaf_script;
        const policy_node_keyexpr_t *ct_k2 = ct_n1->key;
        if (ct_k2->type != KEY_EXPRESSION_MUSIG) break;
        const musig_aggr_key_info_t *ct_mi3 = ct_k2->m.musig_info;
        set_binding_number(&out->bindings, 0, ct_mi3->n);
        set_binding_keys(&out->bindings, 1, ct_k2, 1);
        out->bindings.n = 2;
        out->cls = TC_MULTISIG;
        return true;
    } while (0);

    // Timelocked: and_v(v:$sub, $timelock)
    do {
        if (leaf_script == NULL || leaf_script->type != TOKEN_AND_V) break;
        const policy_node_with_script2_t *ct_n1 = (const policy_node_with_script2_t *) leaf_script;
        const policy_node_t *ct_c2 = ct_n1->scripts[0];
        if (ct_c2 == NULL || ct_c2->type != TOKEN_V) break;
        const policy_node_with_script_t *ct_w3 = (const policy_node_with_script_t *) ct_c2;
        const policy_node_t *ct_c4 = ct_w3->script;
        ct_leaf_match_t ct_sub5;
        if (!match_tapleaf(ct_c4, &ct_sub5)) break;
        if (ct_sub5.cls == TC_OTHER || ct_sub5.cls == TC_TIMELOCKED || ct_sub5.cls == TC_AND_V) break;
        const policy_node_t *ct_c6 = ct_n1->scripts[1];
        ct_timelock_t ct_tl7;
        if (!match_lock_value(ct_c6, &ct_tl7)) break;
        set_binding_sub(&out->bindings, 0, ct_c4);
        set_binding_timelock(&out->bindings, 1, ct_tl7);
        out->bindings.n = 2;
        out->cls = TC_TIMELOCKED;
        return true;
    } while (0);

    // AndV: and_v(v:$sub1, $sub2)
    do {
        if (leaf_script == NULL || leaf_script->type != TOKEN_AND_V) break;
        const policy_node_with_script2_t *ct_n1 = (const policy_node_with_script2_t *) leaf_script;
        const policy_node_t *ct_c2 = ct_n1->scripts[0];
        if (ct_c2 == NULL || ct_c2->type != TOKEN_V) break;
        const policy_node_with_script_t *ct_w3 = (const policy_node_with_script_t *) ct_c2;
        const policy_node_t *ct_c4 = ct_w3->script;
        ct_leaf_match_t ct_sub5;
        if (!match_tapleaf(ct_c4, &ct_sub5)) break;
        if (ct_sub5.cls == TC_OTHER || ct_sub5.cls == TC_TIMELOCKED || ct_sub5.cls == TC_AND_V) break;
        const policy_node_t *ct_c6 = ct_n1->scripts[1];
        ct_leaf_match_t ct_sub7;
        if (!match_tapleaf(ct_c6, &ct_sub7)) break;
        if (ct_sub7.cls == TC_OTHER || ct_sub7.cls == TC_TIMELOCKED || ct_sub7.cls == TC_AND_V) break;
        set_binding_sub(&out->bindings, 0, ct_c4);
        set_binding_sub(&out->bindings, 1, ct_c6);
        out->bindings.n = 2;
        out->cls = TC_AND_V;
        return true;
    } while (0);

    return false;
}

