// Generated by specs/bip388/gen.py. DO NOT EDIT.
// clang-format off

#include "common/cleartext_specs.h"

const char ct_string_pool[] =
    /*     0 */ "Spendable by \0"
    /*    14 */ " alone (Legacy)\0"
    /*    30 */ " alone (SegWit)\0"
    /*    46 */ "Any \0"
    /*    51 */ " of \0"
    /*    56 */ " must sign\0"
    /*    67 */ "Each of \0"
    /*    76 */ " alone (Taproot)\0"
    /*    93 */ "Main path: spendable by \0"
    /*   118 */ "Main path: each of \0"
    /*   138 */ " and \0"
    /*   144 */ " must both sign\0"
    /*   160 */ "any \0"
    /*   165 */ " must sign (sorted)\0"
    /*   185 */ "each of \0"
    /*   194 */ ", \0"
    /*   197 */ " - and also - \0";

static const cleartext_part_t TOP_LEGACY_SINGLE_SIG_PARTS[] = {
    { CT_PART_LITERAL    , 0,    0 },  // "Spendable by "
    { CT_PART_KEY        , 0,    0 },  // $key
    { CT_PART_LITERAL    , 0,   14 },  // " alone (Legacy)"
};

static const cleartext_part_t TOP_SEGWIT_SINGLE_SIG_PARTS[] = {
    { CT_PART_LITERAL    , 0,    0 },  // "Spendable by "
    { CT_PART_KEY        , 0,    0 },  // $key
    { CT_PART_LITERAL    , 0,   30 },  // " alone (SegWit)"
};

static const cleartext_part_t TOP_MULTISIG_PARTS[] = {
    { CT_PART_LITERAL    , 0,   46 },  // "Any "
    { CT_PART_THRESHOLD  , 0,    0 },  // $threshold
    { CT_PART_LITERAL    , 0,   51 },  // " of "
    { CT_PART_KEYS       , 1,    0 },  // $keys
    { CT_PART_LITERAL    , 0,   56 },  // " must sign"
};

static const cleartext_part_t TOP_MULTISIG_PARTS_ALL[] = {
    { CT_PART_LITERAL    , 0,   67 },  // "Each of "
    { CT_PART_KEYS       , 1,    0 },  // $keys
    { CT_PART_LITERAL    , 0,   56 },  // " must sign"
};

static const cleartext_part_t TOP_TAPROOT_KEY_ONLY_PARTS[] = {
    { CT_PART_LITERAL    , 0,    0 },  // "Spendable by "
    { CT_PART_KEY        , 0,    0 },  // $internal_key
    { CT_PART_LITERAL    , 0,   76 },  // " alone (Taproot)"
};

static const cleartext_part_t TOP_TAPROOT_PARTS[] = {
    { CT_PART_LITERAL    , 0,   93 },  // "Main path: spendable by "
    { CT_PART_KEY        , 0,    0 },  // $internal_key
};

static const cleartext_part_t TOP_TAPROOT_MUSIG_PARTS[] = {
    { CT_PART_LITERAL    , 0,  118 },  // "Main path: each of "
    { CT_PART_KEYS       , 1,    0 },  // $keys
    { CT_PART_LITERAL    , 0,   56 },  // " must sign"
};

static const cleartext_part_t LEAF_SINGLE_SIG_PARTS[] = {
    { CT_PART_KEY        , 0,    0 },  // $key
    { CT_PART_LITERAL    , 0,   56 },  // " must sign"
};

static const cleartext_part_t LEAF_BOTH_MUST_SIGN_PARTS[] = {
    { CT_PART_KEY        , 0,    0 },  // $key1
    { CT_PART_LITERAL    , 0,  138 },  // " and "
    { CT_PART_KEY        , 1,    0 },  // $key2
    { CT_PART_LITERAL    , 0,  144 },  // " must both sign"
};

static const cleartext_part_t LEAF_SORTED_MULTISIG_PARTS[] = {
    { CT_PART_LITERAL    , 0,  160 },  // "any "
    { CT_PART_THRESHOLD  , 0,    0 },  // $threshold
    { CT_PART_LITERAL    , 0,   51 },  // " of "
    { CT_PART_KEYS       , 1,    0 },  // $keys
    { CT_PART_LITERAL    , 0,  165 },  // " must sign (sorted)"
};

static const cleartext_part_t LEAF_SORTED_MULTISIG_PARTS_ALL[] = {
    { CT_PART_LITERAL    , 0,  185 },  // "each of "
    { CT_PART_KEYS       , 1,    0 },  // $keys
    { CT_PART_LITERAL    , 0,  165 },  // " must sign (sorted)"
};

static const cleartext_part_t LEAF_MULTISIG_PARTS[] = {
    { CT_PART_LITERAL    , 0,  160 },  // "any "
    { CT_PART_THRESHOLD  , 0,    0 },  // $threshold
    { CT_PART_LITERAL    , 0,   51 },  // " of "
    { CT_PART_KEYS       , 1,    0 },  // $keys
    { CT_PART_LITERAL    , 0,   56 },  // " must sign"
};

static const cleartext_part_t LEAF_MULTISIG_PARTS_ALL[] = {
    { CT_PART_LITERAL    , 0,  185 },  // "each of "
    { CT_PART_KEYS       , 1,    0 },  // $keys
    { CT_PART_LITERAL    , 0,   56 },  // " must sign"
};

static const cleartext_part_t LEAF_TIMELOCKED_PARTS[] = {
    { CT_PART_SUB        , 0,    0 },  // $sub
    { CT_PART_LITERAL    , 0,  194 },  // ", "
    { CT_PART_TIMELOCK   , 1,    0 },  // $timelock
};

static const cleartext_part_t LEAF_AND_V_PARTS[] = {
    { CT_PART_SUB        , 0,    0 },  // $sub1
    { CT_PART_LITERAL    , 0,  197 },  // " - and also - "
    { CT_PART_SUB        , 1,    0 },  // $sub2
};

const cleartext_spec_t CT_TOP_LEVEL_SPECS[DC__COUNT] = {
    [DC_LEGACY_SINGLE_SIG] = { 1, 0, 3, TOP_LEGACY_SINGLE_SIG_PARTS, 0, NULL, 0 },
    [DC_SEGWIT_SINGLE_SIG] = { 2, 0, 3, TOP_SEGWIT_SINGLE_SIG_PARTS, 0, NULL, 0 },
    [DC_MULTISIG] = { 7, 1, 5, TOP_MULTISIG_PARTS, 3, TOP_MULTISIG_PARTS_ALL, 0 },
    [DC_TAPROOT_KEY_ONLY] = { 1, 0, 3, TOP_TAPROOT_KEY_ONLY_PARTS, 0, NULL, 0 },
    [DC_TAPROOT] = { 1, 0, 2, TOP_TAPROOT_PARTS, 0, NULL, 1 },
    [DC_TAPROOT_MUSIG] = { 1, 1, 3, TOP_TAPROOT_MUSIG_PARTS, 0, NULL, 1 },
};

const cleartext_spec_t CT_TAPLEAF_SPECS[TC__COUNT] = {
    [TC_SINGLE_SIG] = { 1, 0, 2, LEAF_SINGLE_SIG_PARTS, 0, NULL, 0 },
    [TC_BOTH_MUST_SIGN] = { 1, 0, 4, LEAF_BOTH_MUST_SIGN_PARTS, 0, NULL, 0 },
    [TC_SORTED_MULTISIG] = { 1, 0, 5, LEAF_SORTED_MULTISIG_PARTS, 3, LEAF_SORTED_MULTISIG_PARTS_ALL, 0 },
    [TC_MULTISIG] = { 2, 1, 5, LEAF_MULTISIG_PARTS, 3, LEAF_MULTISIG_PARTS_ALL, 0 },
    [TC_TIMELOCKED] = { 1, 0, 3, LEAF_TIMELOCKED_PARTS, 0, NULL, 0 },
    [TC_AND_V] = { 1, 0, 3, LEAF_AND_V_PARTS, 0, NULL, 0 },
};

